/**
 * Runtime carton-data loader.
 *
 * Reads the JSON files generated by `scripts/build-cartons.mjs` and exposes
 * helpers that enrich the existing in-code Product arrays without requiring
 * us to re-edit every product file.
 *
 * Strategy:
 *   1. Match by SKU `code` (exact). Most existing TS products have a code.
 *   2. Fallback: match by normalized name. Vilniaus rows + STOCKS rows that
 *      have a name but the TS product lacks a code are caught here.
 *   3. Vilniaus richer specs (mm + pallet + truck) override STOCKS data
 *      because the manufacturer sheet is canonical for that brand.
 *   4. If nothing matches → leave `carton` undefined; UI shows
 *      "Carton specs not yet available".
 *
 * Auto-import of new products (~58 STOCKS rows with full dims that don't
 * map to any existing TS product) lives in `autoImportProducts.ts`.
 */

import type { Product, CartonSpec, CartonExtras } from '@/types';
import cartonsJson from './cartons.json';
import vilniausJson from './cartons-vilniaus.json';
import diploMasterJson from './diplo-master.json';

// ---------------------------------------------------------------------------
// JSON shapes (mirror what build-cartons.mjs emits)
// ---------------------------------------------------------------------------

interface RawCarton {
  code: string;
  name: string;
  supplier: string;
  units_per_carton: number | null;
  length_cm: number | null;
  width_cm: number | null;
  height_cm: number | null;
  weight_kg: number | null;
  volume_m3: number | null;
  hasDims: boolean;
}

interface RawVilniaus {
  raw_name: string;
  brand: string;
  ean: string | null;
  bottle: Record<string, number | null>;
  carton: {
    units_per_carton: number | null;
    weight_kg: number | null;
    length_cm: number | null;
    width_cm: number | null;
    height_cm: number | null;
    volume_m3: number | null;
  };
  pallet: Record<string, number | null>;
  truck: Record<string, number | null>;
}

interface RawMaster {
  code: string;
  name: string;
  product_type: string;
  origin: string | null;
  supplier: string;
  partner_type: string;
  in_container: number | null;
  tc_size: number | null;
}

const stocks = cartonsJson as Record<string, RawCarton>;
const vilniaus = vilniausJson as Record<string, RawVilniaus>;
const master = diploMasterJson as Record<string, RawMaster>;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function normName(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ');
}

/** Pre-built name index for STOCKS — same logic as the Python builder. */
const stocksByName: Record<string, string> = {};
for (const code of Object.keys(stocks)) {
  const item = stocks[code];
  if (item.name) stocksByName[normName(item.name)] = code;
}

/** Pick a sensible "bottle" / "can" / etc. label from a category id. */
function deriveUnitLabel(categoryId: string | undefined): string {
  if (!categoryId) return 'unit';
  const c = categoryId.toLowerCase();
  if (c.includes('beer') || c.includes('energy')) return 'can';
  if (c.includes('wine') || c.includes('whisk') || c.includes('vodka') ||
      c.includes('gin') || c.includes('rum') || c.includes('spirit') ||
      c.includes('cognac') || c.includes('brandy') || c.includes('liqu')) {
    return 'bottle';
  }
  if (c.includes('food') || c.includes('sauce') || c.includes('canned') ||
      c.includes('pasta') || c.includes('biscuit')) {
    return 'jar';
  }
  return 'unit';
}

/** Convert a STOCKS row to a CartonSpec — null if dims incomplete. */
function stocksToCartonSpec(s: RawCarton | undefined): CartonSpec | null {
  if (!s) return null;
  if (!s.length_cm || !s.width_cm || !s.height_cm || !s.weight_kg || !s.units_per_carton) {
    return null;
  }
  const volume_m3 =
    s.volume_m3 ??
    (s.length_cm * s.width_cm * s.height_cm) / 1_000_000;
  return {
    units_per_carton: s.units_per_carton,
    length_cm: s.length_cm,
    width_cm: s.width_cm,
    height_cm: s.height_cm,
    weight_kg: s.weight_kg,
    volume_m3,
  };
}

/** Convert a Vilniaus row's carton block to a CartonSpec. */
function vilniausToCartonSpec(v: RawVilniaus | undefined): CartonSpec | null {
  if (!v) return null;
  const c = v.carton;
  if (!c.length_cm || !c.width_cm || !c.height_cm || !c.weight_kg || !c.units_per_carton) {
    return null;
  }
  return {
    units_per_carton: c.units_per_carton,
    length_cm: c.length_cm,
    width_cm: c.width_cm,
    height_cm: c.height_cm,
    weight_kg: c.weight_kg,
    volume_m3:
      c.volume_m3 ?? (c.length_cm * c.width_cm * c.height_cm) / 1_000_000,
  };
}

function vilniausToExtras(v: RawVilniaus | undefined): CartonExtras | undefined {
  if (!v) return undefined;
  const p = v.pallet;
  const t = v.truck;
  const out: CartonExtras = {};
  if (p.cases_per_layer) out.cases_per_layer = p.cases_per_layer;
  if (p.cases_per_pallet) out.cases_per_pallet = p.cases_per_pallet;
  if (p.units_per_pallet) out.units_per_pallet = p.units_per_pallet;
  if (p.weight_kg) out.pallet_weight_kg = p.weight_kg;
  if (t.pallets_per_truck) out.pallets_per_truck = t.pallets_per_truck;
  if (t.bottles_per_truck) out.bottles_per_truck = t.bottles_per_truck;
  return Object.keys(out).length ? out : undefined;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns a new product object enriched with `carton`, `cartonExtras`, and
 * `unit_label` if matching data was found. Otherwise returns the original
 * product unchanged.
 *
 * Match priority: Vilniaus name → STOCKS code → STOCKS name.
 */
export function enrichProduct(p: Product): Product {
  // 1. Vilniaus rich specs (manufacturer sheet — canonical for the brand)
  const isVilniaus =
    p.partnerSlug === 'vilniaus-degtine' ||
    p.brand?.toLowerCase().includes('vilniaus') ||
    /vilniaus|barska|cepkeliai|el galipote|thorn|seven senses|admiral|three x/i.test(
      p.brand ?? '',
    );
  if (isVilniaus) {
    const key = normName(p.name);
    let v = vilniaus[key];
    // Fuzzy fallback — try matching on the raw name within the dictionary
    if (!v) {
      for (const k of Object.keys(vilniaus)) {
        if (k.includes(key) || key.includes(k)) {
          v = vilniaus[k];
          break;
        }
      }
    }
    const cartonV = vilniausToCartonSpec(v);
    if (cartonV) {
      return {
        ...p,
        carton: cartonV,
        cartonExtras: vilniausToExtras(v),
        unit_label: p.unit_label ?? deriveUnitLabel(p.categoryId),
      };
    }
  }

  // 2. STOCKS by code
  if (p.code) {
    const c = stocksToCartonSpec(stocks[p.code]);
    if (c) {
      return {
        ...p,
        carton: c,
        unit_label: p.unit_label ?? deriveUnitLabel(p.categoryId),
      };
    }
  }

  // 3. STOCKS by normalized name
  const k = normName(p.name);
  const codeByName = stocksByName[k];
  if (codeByName) {
    const c = stocksToCartonSpec(stocks[codeByName]);
    if (c) {
      return {
        ...p,
        carton: c,
        unit_label: p.unit_label ?? deriveUnitLabel(p.categoryId),
      };
    }
  }

  // 4. No match — preserve as-is
  return {
    ...p,
    unit_label: p.unit_label ?? deriveUnitLabel(p.categoryId),
  };
}

/** Enrich an entire product array with carton specs. */
export function enrichProducts(products: Product[]): Product[] {
  return products.map(enrichProduct);
}

// ---------------------------------------------------------------------------
// Stats — useful for dev console / DECISIONS audit trail
// ---------------------------------------------------------------------------

export function countCoverage(products: Product[]): {
  total: number;
  withCarton: number;
  withoutCarton: number;
  withExtras: number;
} {
  let withCarton = 0;
  let withoutCarton = 0;
  let withExtras = 0;
  for (const p of products) {
    if (p.carton) withCarton++; else withoutCarton++;
    if (p.cartonExtras) withExtras++;
  }
  return { total: products.length, withCarton, withoutCarton, withExtras };
}

// Re-export the raw catalogs in case other modules need them (e.g. the
// auto-import flow that creates new products from STOCKS-only rows).
export { stocks as rawStocks, vilniaus as rawVilniaus, master as rawMaster };
