import type { Product } from '@/types';
import { enrichProducts } from '@/data/_generated/cartonsLoader';

// Real product photography (delivered by client). Vite resolves these
// imports to hashed asset URLs at build time.
import imgChateauHibisRouge from '@/assets/products/wines/chateau-hibis-rouge.jpg';
import imgChateauHibisBlanc from '@/assets/products/wines/chateau-hibis-blanc.jpg';
import imgSanNicola1L from '@/assets/products/wines/san-nicola-red-wine.jpeg';
import imgLutteDeLion from '@/assets/products/wines/lutte-de-lion.jpeg';
import imgSanNicolaCabernet from '@/assets/products/wines/chateau-san-nicola-cabernet.jpg';
import imgSanNicolaChardonnay from '@/assets/products/wines/chateau-san-nicola-chardonnay.jpg';
import imgSanNicolaRose from '@/assets/products/wines/chateau-san-nicola-rose.jpg';
import imgSanNicolaSyrah from '@/assets/products/wines/san-nicola-syrah.jpeg';
import imgSanNicolaSangria from '@/assets/products/wines/chateau-san-nicola-cabernet.jpg';
import imgMamaMiaCuvee from '@/assets/products/wines/mama-mia-cuvee-speciale.jpg';
import imgMamaMiaWhiteMoelleux from '@/assets/products/wines/mama-mia-moelleu-main.png';
import imgLuneSoleilCabernet from '@/assets/products/wines/lune-de-soleil-cabernet.jpg';
import imgLuneSoleilBlanc from '@/assets/products/wines/lune-de-soleil-blanc-moelleux.jpg';

// Cropped from the Diplo Catalogue 2026 product spreads — book-mockup
// styling preserved for a premium catalogue feel.
import imgMatzstronglager85 from '@/assets/products/beer/matz-strong-lager-beer-50cl-8.5.png';
import imgMatzstronglager10 from '@/assets/products/beer/matz-strong-lager-beer-50cl-10.png';
import imgMatzstronglager16 from '@/assets/products/beer/matz-strong-lager-beer-50cl-16.png';
import imgMatzstronglager12 from '@/assets/products/beer/matz-strong-lager-beer-50cl-12.png';
import imgMatzClassicWheat from '@/assets/products/beer/matz-classic-wheat-beer-50cl-5.png';
import imgMatzLiteLager from '@/assets/products/beer/matz-lite-lager-beer-50cl-4.5.png';
import imgMatzLager from '@/assets/products/beer/matz-lager-beer-50cl-5.png';
import imgMax12LargeCan from '@/assets/products/energy/max12-500ml.jpeg';
import imgMax12SmallCans from '@/assets/products/spirits/max12-main.png';
import imgBarmixCranberry from '@/assets/products/spirits/barmix-cranberry.png';
import imgBarmixVodkaEnergy from '@/assets/products/spirits/barmix-vodka-energy.png';
import imgBarmixOrange from '@/assets/products/spirits/barmix-orange-non-alcoholic.png';
import imgBarmixCranberryNa from '@/assets/products/spirits/barmix-craneberry-non-alcoholu.png';
import imgBarmixHerbes from '@/assets/products/spirits/barmix-herbes-non-alcoholic.png';
import imgBarmixEnergy from '@/assets/products/spirits/barmix-energy.png';
import imgBarmixHibiscus from '@/assets/products/spirits/barmix-hibiscus-non-acoholic.png';
import imgBarmixHibiscusGinger from '@/assets/products/spirits/barmix-hibiscus-ginger.png';
import imgBarmixBerry from '@/assets/products/spirits/barmix-berry.png';
import imgBarmixTropical from '@/assets/products/spirits/barmix-tropical.png';
import img4KingVodka from '@/assets/products/spirits/4king-vodka-main.png';
import img4KingGin from '@/assets/products/spirits/4king-vodka-main.png';
import imgPastis33 from '@/assets/products/spirits/pastis-33-main.png';
import imgWolfStone from '@/assets/products/spirits/the-wolf-stone premium-whiskey.avif';
import imgKaaptan from '@/assets/products/spirits/kaaptan-main.png';
import imgRosalindaMushroomP from '@/assets/products/food/rosalinda-mushroom-pieces-stem-main.jpeg.png';
import imgRosalindaBakedBeans from '@/assets/products/food/baked-bean-main.png';
import imgRosalindaCanned from '@/assets/products/food/rosalinda-canned.jpg';
import imgRosalindaDarkSoy from '@/assets/products/food/rosalinda-dark-soy-sauce.jpeg';
import imgRosalindaPastaCorn from '@/assets/products/food/rosalinda-spaghetti-main.png';
import imgRosalindaTuna from '@/assets/products/food/rosalinda-sardine.jpeg';
import imgRosalindaMackerel from '@/assets/products/food/rosalinda-mackerel-sauce.jpeg';

// Public-folder PDFs are referenced by absolute path so they stream
// directly from /catalogs/ without bundling.
const TASTING_NOTES_PDF = '/catalogs/diplo-wine-tasting-notes.pdf';
const MAX12_TOOLKIT_PDF = '/catalogs/max12-brand-toolkit.pdf';
/** Master catalogue — surfaced from the Hero "Premium catalog" card and
 *  the Footer downloads strip. */
export const DIPLO_CATALOGUE_PDF = '/catalogs/diplo-catalogue-2026.pdf';

// =====================================================================
// Diplo Private Label SKUs — Diplo's own brands manufactured under
// contract in Spain, Bulgaria, Brazil, Romania, Poland, Ukraine, India,
// Turkey, and China. Sourced from claude/excel-data-dump.txt:
//   - Main "Diplo" sheet rows where partner == PRIVATE LABEL
//   - "diplo private label" sheet (R5-R88) for additional packing variants
//
// All entries carry `isOwnBrand: true`, `partnerType: 'PRIVATE_LABEL'`,
// and `priceOnRequest: true`.  Wine SKUs with delivered photography use
// imported asset paths; everything else still uses `placehold.co` until
// the client supplies real images.
// =====================================================================

/** Helper: construct a placehold.co image URL for an own-brand product. */
function img(text: string, bg = '1E3A8A', fg = 'FCD34D'): string {
  return `https://placehold.co/800x600/${bg}/${fg}?text=${encodeURIComponent(text)}`;
}

// Raw catalog (hand-authored). The exported `ownProducts` below applies
// `enrichProducts()` so each entry picks up its `carton` spec from the
// Excel-driven JSON in `_generated/`. Hand-edit this array — never the JSON.
const ownProductsRaw: Product[] = [
  // ─── MATZ Beer (Ukraine / Poland) ───────────────────────────────
  {
    id: 'own-matz-8.5-50',
    slug: 'matz-beer-8.5-50cl',
    name: 'MATZ Beer 8.5% — 24×50cl',
    code: '39-860',
    brand: 'MATZ',
    description: 'Strong export lager bottled in Gdansk for the West African trade. 8.5% ABV, premium glass bottle, distinctive black-and-gold livery.',
    shortDescription: 'Strong 8.5% lager in 50cl bottles — flagship MATZ.',
    categoryId: 'beer',
    image: imgMatzstronglager85,
    origin: 'Poland — Gdansk',
    supplier: 'Diplo / IMI International',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2050,
    tcSize: 40,
    packing: '24×50cl',
    volume: '0.50L',
    alcoholContent: 8.5,
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: 'own-matz-10-50',
    slug: 'matz-beer-10-50cl',
    name: 'MATZ Beer 10% — 24×50cl',
    code: '39-861',
    brand: 'MATZ',
    description: 'Premium high-strength lager — 10% ABV — brewed for export and distributed by Diplo across the region.',
    shortDescription: 'Premium 10% MATZ lager — 50cl glass.',
    categoryId: 'beer',
    image: imgMatzstronglager10,
    origin: 'Poland — Gdansk',
    supplier: 'Diplo / IMI International',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2060,
    tcSize: 40,
    packing: '24×50cl',
    volume: '0.5L',
    alcoholContent: 10,
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
  },
  {
    id: 'own-matz-16-50',
    slug: 'matz-beer-16-50cl',
    name: 'MATZ 16% — 24×50cl',
    brand: 'MATZ',
    shortDescription: 'Compact 50cl format of MATZ 16%.',
    categoryId: 'beer',
    image: imgMatzstronglager16,
    origin: 'Ukraine',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×50cl',
    volume: '0.50L',
    alcoholContent: 16,
    priceOnRequest: true,
    isOwnBrand: true,
  },
  {
    id: 'own-matz-12-can',
    slug: 'matz-beer-12-can',
    name: 'MATZ 12% Can — 24×50cl',
    brand: 'MATZ',
    shortDescription: 'Easy-drinking 12% MATZ in 50cl can format.',
    categoryId: 'beer',
    image: imgMatzstronglager12,
    origin: 'Ukraine',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×50cl can',
    volume: '0.50L',
    alcoholContent: 12,
    priceOnRequest: true,
    isOwnBrand: true,
  },{
    id: 'own-matz-5-can',
    slug: 'matz-beer-5-can',
    name: 'MATZ 5% Can — 24×50cl',
    brand: 'MATZ',
    shortDescription: 'Easy-drinking 5% MATZ in 50cl can format.',
    categoryId: 'beer',
    image: imgMatzClassicWheat,
    origin: 'Ukraine',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×50cl can',
    volume: '0.50L',
    alcoholContent: 5,
    priceOnRequest: true,
    isOwnBrand: true,
  },{
    id: 'own-matz-4.5-can',
    slug: 'matz-beer-4.5-can',
    name: 'MATZ .4.5% Can — 24×50cl',
    brand: 'MATZ',
    shortDescription: 'Easy-drinking 5% MATZ in 50cl can format.',
    categoryId: 'beer',
    image: imgMatzLiteLager,
    origin: 'Ukraine',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×50cl can',
    volume: '0.50L',
    alcoholContent: 4.5,
    priceOnRequest: true,
    isOwnBrand: true,
  },{
    id: 'own-matz-4.5-can',
    slug: 'matz-beer-4.5-can',
    name: 'MATZ 4.5% Can — 24×50cl',
    brand: 'MATZ',
    shortDescription: 'Easy-drinking 4.5% MATZ in 50cl can format.',
    categoryId: 'beer',
    image: imgMatzLager,
    origin: 'Ukraine',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×33cl can',
    volume: '0.50L',
    alcoholContent: 4.5,
    priceOnRequest: true,
    isOwnBrand: true,
  },
  




  // ─── 4KING (Romania / Moldova) ──────────────────────────────────
  {
    id: 'own-4king-vodka',
    slug: '4king-vodka',
    name: '4KING Vodka 40% — 6×1.75L',
    code: '38-760',
    brand: '4KING',
    description: 'Magnum-format premium vodka. 40% ABV. Distilled and bottled in Romania for distribution across West Africa.',
    shortDescription: 'Magnum 1.75L premium vodka — 40% ABV.',
    categoryId: 'vodka',
    image: img4KingVodka,
    origin: 'Romania — Constanta',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 800,
    tcSize: 20,
    packing: '6×1.75L',
    volume: '1.75L',
    alcoholContent: 40,
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
  },
  {
    id: 'own-4king-gin',
    slug: '4king-gin',
    name: '4KING Gin 40% — 6×1.75L',
    code: '38-761',
    brand: '4KING',
    description: 'Magnum-format dry gin matching the 4KING vodka livery. 40% ABV.',
    shortDescription: 'Magnum 1.75L dry gin — 40% ABV.',
    categoryId: 'gin',
    image: img4KingGin,
    origin: 'Romania — Constanta',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 800,
    tcSize: 20,
    packing: '6×1.75L',
    volume: '1.75L',
    alcoholContent: 40,
    priceOnRequest: true,
    isOwnBrand: true,
  },

  // ─── Chateau Hibis (Spain) ──────────────────────────────────────
  {
    id: 'own-chateau-hibis-red',
    slug: 'chateau-hibis-red',
    name: 'Chateau Hibis Red 14% — 6×75cl',
    code: '37-582',
    brand: 'Chateau Hibis',
    description: 'Full-bodied Spanish red wine bottled for Diplo. 14% ABV, six-pack carton.',
    shortDescription: 'Full-bodied Spanish red — 14% ABV.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgChateauHibisRouge,
    origin: 'Spain — Valencia',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2500,
    tcSize: 20,
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 14,
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
    brochureUrl: TASTING_NOTES_PDF,
  },
  {
    id: 'own-chateau-hibis-white',
    slug: 'chateau-hibis-white',
    name: 'Chateau Hibis White 11% — 6×75cl',
    code: '37-584',
    brand: 'Chateau Hibis',
    shortDescription: 'Crisp Spanish white — 11% ABV.',
    categoryId: 'wine',
    subCategoryId: 'white',
    image: imgChateauHibisBlanc,
    origin: 'Spain — Valencia',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2500,
    tcSize: 20,
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 11,
    priceOnRequest: true,
    isOwnBrand: true,
  },

  // ─── Mama Mia (Spain / Bulgaria) ────────────────────────────────
  {
    id: 'own-mama-mia-white-moelleux',
    slug: 'mama-mia-white-moelleux',
    name: 'Mama Mia White Moelleux — 6×75cl',
    code: '18-529',
    brand: 'Mama Mia',
    description: 'Sweet Spanish white in the iconic Mama Mia livery. A Diplo bestseller.',
    shortDescription: 'Sweet Spanish white moelleux.',
    categoryId: 'wine',
    subCategoryId: 'white',
    image: imgMamaMiaWhiteMoelleux,
    origin: 'Spain — Algeciras',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2950,
    tcSize: 20,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
    brochureUrl: TASTING_NOTES_PDF,
  },
  {
    id: 'own-mama-mia-red',
    slug: 'mama-mia-red',
    name: 'Mama Mia Red Cuvée Spéciale 14% — 6×75cl',
    code: '18-509',
    brand: 'Mama Mia',
    description:
      'Mama Mia Cuvée Spéciale — full-bodied Spanish red wine, 14% ABV. Pleasant sweetness with red-fruit aromas. Pairs naturally with pasta, red and marbled meat.',
    shortDescription: 'Full-bodied Mama Mia red Cuvée Spéciale — 14% ABV.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgMamaMiaCuvee,
    origin: 'Spain — Algeciras',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2590,
    tcSize: 20,
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 14,
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
    brochureUrl: TASTING_NOTES_PDF,
    tastingNotes: {
      appearance: 'Intense red color with pronounced violet tones.',
      nose: 'Pleasant sweetness balance with notes of red fruits.',
      pairing: 'Pairs nicely with pasta, red meat, or marbled meat.',
    },
  },
  // {
  //   id: 'own-mama-mia-bulgaria-white',
  //   slug: 'mama-mia-bulgaria-white-1l',
  //   name: 'Mama Mia White 1L — 6×100cl',
  //   brand: 'Mama Mia',
  //   shortDescription: 'Bulgarian-bottled Mama Mia white in 1L format.',
  //   categoryId: 'wine',
  //   subCategoryId: 'white',
  //   image: img('MAMA MIA\\n1L WHITE', 'FBBF24', '1E3A8A'),
  //   origin: 'Bulgaria',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '6×100cl',
  //   volume: '1L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  // {
  //   id: 'own-mama-mia-bulgaria-red',
  //   slug: 'mama-mia-bulgaria-red-1l',
  //   name: 'Mama Mia Red 1L — 6×100cl',
  //   brand: 'Mama Mia',
  //   shortDescription: 'Bulgarian-bottled Mama Mia red in 1L format.',
  //   categoryId: 'wine',
  //   subCategoryId: 'red',
  //   image: img('MAMA MIA\\n1L RED', '7F1D1D', 'FCD34D'),
  //   origin: 'Bulgaria',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '6×100cl',
  //   volume: '1L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },

  // ─── Chateau San Nicola / St Nicholas ───────────────────────────
  {
    id: 'own-csn-syrah-15',
    slug: 'chateau-san-nicola-syrah-1-5l',
    name: 'Chateau San Nicola Cabernet Syrah 14% — 6×1.5L',
    code: '18-036',
    brand: 'Chateau San Nicola',
    description:
      'Magnum-format Cabernet Sauvignon. A young wine with bright red ruby colour and purple tones — perfect for daily enjoyment, especially with grilled or smoked meat.',
    shortDescription: 'Magnum Cabernet Sauvignon, 14% ABV.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgSanNicolaSyrah,
    brochureUrl: TASTING_NOTES_PDF,
    tastingNotes: {
      appearance: 'Young wine, bright red ruby colour with purple tones and medium layer.',
      nose: 'Red fruits aroma.',
      pairing: 'The perfect wine for daily — pairs well with meat and grilled / smoked food.',
    },
    origin: 'Spain — Algeciras',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 1250,
    tcSize: 20,
    packing: '6×1.5L',
    volume: '1.5L',
    alcoholContent: 14,
    priceOnRequest: true,
    isOwnBrand: true,
  },
  // {
  //   id: 'own-csn-tetra-red',
  //   slug: 'chateau-san-nicola-tetra-red',
  //   name: 'Chateau San Nicola Tetra Red 13% — 12×1L',
  //   code: '18-035',
  //   brand: 'Chateau San Nicola',
  //   shortDescription: 'Tetra-pack red wine — 1L slim format, 13% ABV.',
  //   categoryId: 'wine',
  //   subCategoryId: 'red',
  //   image: img('SAN NICOLA\\nTETRA', '7F1D1D', 'FCD34D'),
  //   origin: 'Spain — Algeciras',
  //   partnerType: 'PRIVATE_LABEL',
  //   containerQty: 1752,
  //   tcSize: 20,
  //   packing: '12×1L tetra',
  //   volume: '1L',
  //   alcoholContent: 13,
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  {
    id: 'own-csn-sangria',
    slug: 'chateau-san-nicola-sangria',
    name: 'Chateau San Nicola Sangria 12% — 12×1L',
    code: '19-342',
    brand: 'Chateau San Nicola',
    description:
      'A party drink — cherry red, very bright, with notes of raspberry and orange. Slightly sweet and fruity. Serve chilled with paella, tapas, or with ice and citrus.',
    shortDescription: 'Tetra sangria — fruity, 12% ABV.',
    categoryId: 'wine',
    subCategoryId: 'sangria',
    image: imgSanNicolaSangria,
    brochureUrl: TASTING_NOTES_PDF,
    tastingNotes: {
      appearance: 'Cherry red, very bright.',
      nose: 'Intense aromas of ripe red fruit.',
      palate:
        'Notes of raspberry and orange — fresh, sweet, fruity. Slightly sweet, with a friendly entry on the palate.',
      pairing:
        'Serve with paella, tapas, or just olives and almonds. Chill with ice cubes and citrus.',
    },
    origin: 'Spain — Algeciras',
    partnerType: 'PRIVATE_LABEL',
    packing: '12×1L tetra',
    volume: '1L',
    alcoholContent: 12,
    priceOnRequest: true,
    isOwnBrand: true,
  },
  // {
  //   id: 'own-csn-brut',
  //   slug: 'chateau-san-nicola-brut',
  //   name: 'Chateau San Nicola Sparkling Brut 12% — 6×75cl',
  //   code: '18-056',
  //   brand: 'Chateau San Nicola',
  //   description:
  //     'Sparkling Brut white wine — fine bubbles, delicate fruit, ideal for sharing. Yellow with greenish tones; balanced acidity.',
  //   shortDescription: 'Sparkling brut white — 12% ABV.',
  //   categoryId: 'wine',
  //   subCategoryId: 'sparkling',
  //   image: imgSanNicolaChardonnay,
  //   brochureUrl: TASTING_NOTES_PDF,
  //   tastingNotes: {
  //     appearance: 'Nice yellow color with greenish tones.',
  //     nose: 'Delicate fruits with good acid balance — white peach, fruity and elegant.',
  //     palate: 'Fine bubbles invade the palate, exalting the nose with a finesse of its own.',
  //     pairing:
  //       'Ideal with appetizers, smoked salmon, seafood, fresh fish, and desserts. Perfect for sharing.',
  //   },
  //   origin: 'Spain — Algeciras',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '6×75cl',
  //   volume: '0.75L',
  //   alcoholContent: 12,
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  {
    id: 'own-st-nicholas-red-1l',
    slug: 'st-nicholas-red-1l',
    name: 'St Nicholas Red 1L — 6×100cl',
    code: '37-569',
    brand: 'St Nicholas',
    shortDescription: 'St Nicholas Red — Bulgarian bottling.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgSanNicola1L,
    origin: 'Bulgaria — Varna',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2500,
    tcSize: 40,
    packing: '6×100cl',
    volume: '1L',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  {
    id: 'own-st-nicholas-rose-1l',
    slug: 'st-nicholas-rose-1l',
    name: 'St Nicholas Rose 1L — 6×100cl',
    code: '37-571',
    brand: 'St Nicholas',
    shortDescription: 'Bulgarian rose — 1L format.',
    categoryId: 'wine',
    subCategoryId: 'rose',
    image: imgSanNicolaRose,
    origin: 'Bulgaria — Varna',
    partnerType: 'PRIVATE_LABEL',
    packing: '6×100cl',
    volume: '1L',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  // {
  //   id: 'own-st-nicholas-white-1l',
  //   slug: 'st-nicholas-white-1l',
  //   name: 'St Nicholas White 1L — 6×100cl',
  //   code: '37-570',
  //   brand: 'St Nicholas',
  //   shortDescription: 'Bulgarian white — 1L format.',
  //   categoryId: 'wine',
  //   subCategoryId: 'white',
  //   image: img('ST NICHOLAS\\nWHITE', 'FBBF24', '1E3A8A'),
  //   origin: 'Bulgaria — Varna',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '6×100cl',
  //   volume: '1L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },

  // ─── Lune de Soleil (premium private label) ─────────────────────
  // Premium-tier wine line introduced 2024–2025. Two SKUs delivered so
  // far (Cabernet Sauvignon + Blanc Moelleux). TODO: confirm origin,
  // packing, container/MOQ once client provides spec sheet.
  {
    id: 'own-lune-soleil-cabernet',
    slug: 'lune-de-soleil-cabernet-sauvignon-2024',
    name: 'Lune de Soleil Cabernet Sauvignon 2024 — 6×75cl',
    brand: 'Lune de Soleil',
    description:
      'Premium-tier Cabernet Sauvignon, Sélection Supérieure. 16% ABV in a bold black-and-gold livery. The Lune de Soleil line is Diplo\'s flagship private-label wine, launched in 2024.',
    shortDescription: 'Premium Cabernet Sauvignon — 16% ABV, Sélection Supérieure.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgLuneSoleilCabernet,
    // TODO: confirm exact origin / packing / container quantity with client.
    partnerType: 'PRIVATE_LABEL',
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 16,
    vintage: '2024',
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
  },
  {
    id: 'own-lune-soleil-blanc',
    slug: 'lune-de-soleil-blanc-moelleux-2025',
    name: 'Lune de Soleil Blanc Moelleux 2025 — 6×75cl',
    brand: 'Lune de Soleil',
    description:
      'Premium-tier sweet white — Blanc Moelleux 2025, Sélection Supérieure. 12% ABV. Lune de Soleil signature livery in cream and gold.',
    shortDescription: 'Premium Blanc Moelleux — 12% ABV, Sélection Supérieure.',
    categoryId: 'wine',
    subCategoryId: 'white',
    image: imgLuneSoleilBlanc,
    // TODO: confirm exact origin / packing / container quantity with client.
    partnerType: 'PRIVATE_LABEL',
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 12,
    vintage: '2025',
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
  },

  // ─── Luttes Des Lions (France) ──────────────────────────────────
  {
    id: 'own-luttes-des-lions',
    slug: 'luttes-des-lions-bordeaux',
    name: 'Luttes Des Lions Bordeaux — 6×75cl',
    code: '38-950',
    brand: 'Luttes Des Lions',
    description: 'Diplo private-label Bordeaux — 14% ABV. French bottling, premium gift-style livery.',
    shortDescription: 'Private-label Bordeaux — 14% ABV.',
    categoryId: 'wine',
    subCategoryId: 'bordeaux',
    image: imgLutteDeLion,
    origin: 'France — Le Havre',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2750,
    tcSize: 20,
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 14,
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
  },

  // ─── MAX12 Energy Drinks (Poland) ───────────────────────────────
  {
    id: 'own-max12-250',
    slug: 'max12-energy-250ml',
    name: 'MAX12 Energy Drink — 24×25cl',
    brand: 'MAX12',
    description: 'High-energy can — short-can format. Compact 250ml serving.',
    shortDescription: 'MAX12 Energy in 250ml short cans.',
    categoryId: 'energy-drink',
    image: imgMax12SmallCans,
    origin: 'Poland — Gdynia',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×25cl',
    volume: '0.25L',
    priceOnRequest: true,
    isOwnBrand: true,
    brochureUrl: MAX12_TOOLKIT_PDF,
  },
  // {
  //   id: 'own-max12-330',
  //   slug: 'max12-energy-330ml',
  //   name: 'MAX12 Energy Drink — 24×33cl',
  //   code: '39-066',
  //   brand: 'MAX12',
  //   shortDescription: 'MAX12 Energy in 330ml cans.',
  //   categoryId: 'energy-drink',
  //   image: imgMax12LargeCan,
  //   origin: 'Poland — Gdynia',
  //   partnerType: 'PRIVATE_LABEL',
  //   containerQty: 2700,
  //   tcSize: 40,
  //   packing: '24×33cl',
  //   volume: '0.33L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  //   isFeatured: true,
  //   brochureUrl: MAX12_TOOLKIT_PDF,
  // },
  {
    id: 'own-max12-500',
    slug: 'max12-energy-500ml',
    name: 'MAX12 Energy Drink — 24×50cl',
    brand: 'MAX12',
    shortDescription: 'MAX12 Energy in 500ml cans.',
    categoryId: 'energy-drink',
    image: imgMax12LargeCan,
    origin: 'Poland — Gdynia',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×50cl',
    volume: '0.5L',
    priceOnRequest: true,
    isOwnBrand: true,
    brochureUrl: MAX12_TOOLKIT_PDF,
  },

  // ─── BARMIX Vodka Mix (Poland) ──────────────────────────────────
  {
    id: 'own-barmix-berry-250',
    slug: 'barmix-berry-250ml',
    name: 'BARMIX Berry Vodka — 24×25cl',
    brand: 'BARMIX',
    description: 'Berry-flavoured vodka mix — taurine-free, caffeine-free.',
    shortDescription: 'Berry vodka mix — no taurine, no caffeine.',
    categoryId: 'vodka-mix',
    image: imgBarmixBerry,
    origin: 'Poland',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×25cl',
    volume: '0.25L',
    alcoholContent: 18,
    priceOnRequest: true,
    isOwnBrand: true,
  },
  {
    id: 'own-barmix-tropical-250',
    slug: 'barmix-tropical-250ml',
    name: 'BARMIX Tropical Vodka — 24×25cl',
    brand: 'BARMIX',
    shortDescription: 'Tropical vodka mix — 250ml.',
    categoryId: 'vodka-mix',
    image: imgBarmixTropical,
    origin: 'Poland',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×25cl',
    volume: '0.25L',
    alcoholContent: 18,
    priceOnRequest: true,
    isOwnBrand: true,
  },
  {
    id: 'own-barmix-energy-250',
    slug: 'barmix-vodka-energy-250ml',
    name: 'BARMIX Vodka Energy 18% — 25cl×24',
    code: '39-065',
    brand: 'BARMIX',
    shortDescription: 'No taurine, no caffeine vodka energy mix — 18% ABV.',
    categoryId: 'vodka-mix',
    image: imgBarmixVodkaEnergy,
    origin: 'Poland — Gdynia',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 3600,
    tcSize: 40,
    packing: '24×25cl',
    volume: '0.25L',
    alcoholContent: 18,
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
  },
  {
    id: 'own-barmix-herbal-250',
    slug: 'barmix-herbal-250ml',
    name: 'BARMIX Herbal — 24×25cl',
    brand: 'BARMIX',
    shortDescription: 'Herbal-style spirit mix.',
    categoryId: 'herbal',
    image: imgBarmixHerbes,
    origin: 'Poland',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×25cl',
    volume: '0.25L',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  {
    id: 'own-barmix-berry-330',
    slug: 'barmix-berry-330ml',
    name: 'BARMIX Berry Vodka — 24×33cl',
    brand: 'BARMIX',
    shortDescription: 'Berry vodka mix — 330ml format.',
    categoryId: 'vodka-mix',
    image: imgBarmixCranberryNa,
    origin: 'Poland',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×33cl',
    volume: '0.33L',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  {
    id: 'own-barmix-orange-500',
    slug: 'barmix-tropical-500ml',
    name: 'BARMIX Orange Vodka — 24×50cl',
    brand: 'BARMIX',
    shortDescription: 'Orange vodka mix — 500ml.',
    categoryId: 'vodka-mix',
    image: imgBarmixOrange,
    origin: 'Poland',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×50cl',
    volume: '0.5L',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  { id: 'own-barmix-hibiscus-500',
    slug: 'barmix-tropical-500ml',
    name: 'BARMIX Hibiscus Vodka — 24×50cl',
    brand: 'BARMIX',
    shortDescription: 'Hibiscus vodka mix — 500ml.',
    categoryId: 'vodka-mix',
    image: imgBarmixHibiscus,
    origin: 'Poland',
    partnerType: 'PRIVATE_LABEL',
    packing: '24×50cl',
    volume: '0.5L',
    priceOnRequest: true,
    isOwnBrand: true,
  },

  // ─── LANIKA (Brazil) ────────────────────────────────────────────
  // {
  //   id: 'own-lanika',
  //   slug: 'lanika-catuaba',
  //   name: 'LANIKA 16% — 12×500ml',
  //   code: '37-626',
  //   brand: 'LANIKA',
  //   description: 'Brazilian Catuaba spirit drink. 16% ABV.',
  //   shortDescription: 'Brazilian Catuaba — 16% ABV.',
  //   categoryId: 'spirit-drink',
  //   image: img('LANIKA', '7F1D1D', 'FCD34D'),
  //   origin: 'Brazil — Rio Grande',
  //   partnerType: 'PRIVATE_LABEL',
  //   containerQty: 2450,
  //   tcSize: 20,
  //   packing: '12×500ml',
  //   volume: '0.5L',
  //   alcoholContent: 16,
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },

  // ─── Kaaptan / Kaptaan / Wolfstone (India) ──────────────────────
  // {
  //   id: 'own-kaaptan-coffee-rum-75',
  //   slug: 'kaaptan-coffee-rum-75cl',
  //   name: 'Kaaptan Coffee Rum 75cl — 12-pack',
  //   brand: 'Kaaptan',
  //   description: 'Indian coffee-flavoured rum — Diplo private label.',
  //   shortDescription: 'Coffee-flavoured Indian rum.',
  //   categoryId: 'rum',
  //   subCategoryId: 'cafe',
  //   image: img('KAAPTAN\\nCOFFEE RUM', '4A2C1A', 'FCD34D'),
  //   origin: 'India',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '12×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  {
    id: 'own-kaaptan-whiskey-75',
    slug: 'kaaptan-whiskey-75cl',
    name: 'Kaaptan Whiskey 75cl — 12-pack',
    brand: 'Kaaptan',
    shortDescription: 'Indian blended whiskey.',
    categoryId: 'whiskey',
    image: imgKaaptan,
    origin: 'India',
    partnerType: 'PRIVATE_LABEL',
    packing: '12×75cl',
    volume: '0.75L',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  // {
  //   id: 'own-kaaptan-white-rum',
  //   slug: 'kaaptan-white-rum-75cl',
  //   name: 'Kaaptan White Rhum 75cl — 12-pack',
  //   brand: 'Kaaptan',
  //   shortDescription: 'Crisp Indian white rum.',
  //   categoryId: 'rum',
  //   subCategoryId: 'white',
  //   image: img('KAAPTAN\\nWHITE RUM', 'F8FAFC', '1E3A8A'),
  //   origin: 'India',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '12×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  // {
  //   id: 'own-kaptaan-xxx-rum',
  //   slug: 'kaptaan-xxx-dark-rum',
  //   name: 'Kaptaan XXX Dark Rum — 12×75cl',
  //   brand: 'Kaptaan',
  //   shortDescription: 'Dark Indian rum.',
  //   categoryId: 'rum',
  //   subCategoryId: 'dark',
  //   image: img('KAPTAAN\\nXXX DARK', '4A2C1A', 'FCD34D'),
  //   origin: 'India',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '12×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  {
    id: 'own-wolfstone-75',
    slug: 'wolfstone-whiskey-75cl',
    name: 'Wolfstone Whiskey — 12×75cl (Mono)',
    brand: 'Wolfstone',
    shortDescription: 'Premium Indian whiskey, mono carton.',
    categoryId: 'whiskey',
    image: imgWolfStone,
    origin: 'India',
    partnerType: 'PRIVATE_LABEL',
    packing: '12×75cl',
    volume: '0.75L',
    priceOnRequest: true,
    isOwnBrand: true,
  },

  // ─── OKI Cooking Oil (Turkey) ───────────────────────────────────
  // {
  //   id: 'own-oki-25l',
  //   slug: 'oki-cooking-oil-25l',
  //   name: 'OKI Cooking Oil — 25L Yellow Jerry Can',
  //   brand: 'OKI',
  //   description: 'Bulk cooking oil in 25L jerrycan format. Distributed across West Africa.',
  //   shortDescription: 'Bulk 25L jerrycan cooking oil.',
  //   categoryId: 'cooking-oil',
  //   image: img('OKI\\n25L', 'FCD34D', '1E3A8A'),
  //   origin: 'Turkey',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '1×25L',
  //   volume: '25L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  //   isFeatured: true,
  // },

  // ─── Rosalinda (Turkey / China) ─────────────────────────────────
  {
    id: 'own-rosalinda-spaghetti-500',
    slug: 'rosalinda-spaghetti-500g',
    name: 'Rosalinda Spaghetti 500g — 20-pack',
    code: '28-652',
    brand: 'Rosalinda',
    description: 'Diplo private-label durum-wheat spaghetti, Turkish-milled.',
    shortDescription: 'Durum spaghetti — 500g, 20-pack.',
    categoryId: 'pasta',
    image: imgRosalindaPastaCorn,
    origin: 'Turkey — Iskenderun',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 2700,
    tcSize: 20,
    packing: '20×500g',
    priceOnRequest: true,
    isOwnBrand: true,
    isFeatured: true,
  },
  // {
  //   id: 'own-rosalinda-spaghetti-200',
  //   slug: 'rosalinda-spaghetti-200g',
  //   name: 'Rosalinda Spaghetti 200g — 40-pack',
  //   code: '28-657',
  //   brand: 'Rosalinda',
  //   shortDescription: 'Compact 200g spaghetti format.',
  //   categoryId: 'pasta',
  //   image: imgRosalindaPastaCorn,
  //   origin: 'Turkey — Iskenderun',
  //   partnerType: 'PRIVATE_LABEL',
  //   containerQty: 3250,
  //   tcSize: 20,
  //   packing: '40×200g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  {
    id: 'own-rosalinda-soy',
    slug: 'rosalinda-dark-soy-500',
    name: 'Rosalinda Dark Soy Sauce 500ml',
    brand: 'Rosalinda',
    shortDescription: 'Premium dark soy sauce — 500ml glass.',
    categoryId: 'sauces',
    image: imgRosalindaDarkSoy,
    origin: 'China',
    partnerType: 'PRIVATE_LABEL',
    packing: '12×500ml',
    volume: '0.5L',
    priceOnRequest: true,
    isOwnBrand: true,
  },

  // ─── BAHAR (Turkey) ─────────────────────────────────────────────
  // {
  //   id: 'own-bahar-spaghetti-500',
  //   slug: 'bahar-spaghetti-500g',
  //   name: 'BAHAR Spaghetti 500g — 20-pack',
  //   brand: 'BAHAR',
  //   shortDescription: 'Turkish durum spaghetti — value range.',
  //   categoryId: 'pasta',
  //   image: img('BAHAR\\nSPAGHETTI', 'FBBF24', '7F1D1D'),
  //   origin: 'Turkey',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '20×500g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },

  // ─── Sunflower Oil (China) ──────────────────────────────────────
  // {
  //   id: 'own-sunflower-09',
  //   slug: 'sunflower-oil-0-9l',
  //   name: 'Sunflower Oil 0.9L — 12-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Refined sunflower oil — 900ml retail bottle.',
  //   categoryId: 'cooking-oil',
  //   image: img('SUNFLOWER\\nOIL 0.9L', 'FCD34D', '1E3A8A'),
  //   origin: 'China',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '12×900ml',
  //   volume: '0.9L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  // {
  //   id: 'own-sunflower-18',
  //   slug: 'sunflower-oil-1-8l',
  //   name: 'Sunflower Oil 1.8L — 6-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Family-size sunflower oil.',
  //   categoryId: 'cooking-oil',
  //   image: img('SUNFLOWER\\n1.8L', 'FCD34D', '1E3A8A'),
  //   origin: 'China',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '6×1.8L',
  //   volume: '1.8L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  // {
  //   id: 'own-sunflower-5',
  //   slug: 'sunflower-oil-5l',
  //   name: 'Sunflower Oil 5L — 4-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Catering-format sunflower oil.',
  //   categoryId: 'cooking-oil',
  //   image: img('SUNFLOWER\\n5L', 'FCD34D', '1E3A8A'),
  //   origin: 'China',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '4×5L',
  //   volume: '5L',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },

  // ─── Canned Goods (China) ───────────────────────────────────────
  // {
  //   id: 'own-mackerel-155',
  //   slug: 'mackerel-tomato-155g',
  //   name: 'Mackerel in Tomato Sauce 155g — 50-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Single-serve mackerel tin.',
  //   categoryId: 'canned-goods',
  //   image: imgRosalindaMackerel,
  //   origin: 'China — Xiamen',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '50×155g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  // {
  //   id: 'own-mackerel-425',
  //   slug: 'mackerel-tomato-425g',
  //   name: 'Mackerel in Tomato Sauce 425g — 24-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Family-size mackerel tin.',
  //   categoryId: 'canned-goods',
  //   image: imgRosalindaCanned,
  //   origin: 'China',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '24×425g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  // {
  //   id: 'own-geisha-mackerel',
  //   slug: 'geisha-mackerel-50',
  //   name: 'Geisha Mackerel — 50×155g',
  //   code: '12-222',
  //   brand: 'Geisha',
  //   shortDescription: 'Diplo-imported Geisha mackerel tins.',
  //   categoryId: 'canned-goods',
  //   image: imgRosalindaTuna,
  //   origin: 'China — Xiamen',
  //   partnerType: 'PRIVATE_LABEL',
  //   containerQty: 1930,
  //   tcSize: 20,
  //   packing: '50×155g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  {
    id: 'own-mushroom-pieces',
    slug: 'mushroom-pieces-stem-425g',
    name: 'Mushroom Pieces & Stem 425g — 12-pack',
    brand: 'Diplo',
    shortDescription: 'Canned mushroom pieces.',
    categoryId: 'canned-goods',
    image: imgRosalindaMushroomP,
    origin: 'China',
    partnerType: 'PRIVATE_LABEL',
    packing: '12×425g',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  // {
  //   id: 'own-whole-mushroom',
  //   slug: 'whole-mushroom-425g',
  //   name: 'Whole Mushroom 425g — 12-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Whole-cap canned mushrooms.',
  //   categoryId: 'canned-goods',
  //   image: imgRosalindaMushroomP,
  //   origin: 'China',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '12×425g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  // {
  //   id: 'own-green-peas',
  //   slug: 'green-peas-400g',
  //   name: 'Green Peas 400g — 12-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Canned green peas.',
  //   categoryId: 'canned-goods',
  //   image: img('GREEN\\nPEAS', '14532D', 'FCD34D'),
  //   origin: 'China',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '12×400g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },
  {
    id: 'own-baked-beans',
    slug: 'baked-beans-420g',
    name: 'Baked Beans 420g — 12-pack',
    brand: 'Diplo',
    shortDescription: 'Tomato-sauce baked beans.',
    categoryId: 'canned-goods',
    image: imgRosalindaBakedBeans,
    origin: 'China',
    partnerType: 'PRIVATE_LABEL',
    packing: '12×420g',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  {
    id: 'own-sardines',
    slug: 'sardines-125g',
    name: 'Sardines 125g — 50-pack',
    brand: 'Diplo',
    shortDescription: 'Sardines in oil — 125g tins.',
    categoryId: 'canned-goods',
    image: imgRosalindaTuna,
    origin: 'China',
    partnerType: 'PRIVATE_LABEL',
    packing: '50×125g',
    priceOnRequest: true,
    isOwnBrand: true,
  },
  // {
  //   id: 'own-sweet-corn',
  //   slug: 'sweet-corn-340g',
  //   name: 'Sweet Corn 340g — 12-pack',
  //   brand: 'Diplo',
  //   shortDescription: 'Canned sweet corn.',
  //   categoryId: 'canned-goods',
  //   image: imgRosalindaPastaCorn,
  //   origin: 'China',
  //   partnerType: 'PRIVATE_LABEL',
  //   packing: '12×340g',
  //   priceOnRequest: true,
  //   isOwnBrand: true,
  // },

  // ─── Pastis 33 (France) ─────────────────────────────────────────
  {
    id: 'own-pastis-33',
    slug: 'pastis-33',
    name: 'Pastis 33 — 12×1L',
    code: '80-687',
    brand: 'Pastis 33',
    shortDescription: 'Anise-flavoured aperitif — Diplo private label.',
    categoryId: 'liquor',
    image: imgPastis33,
    origin: 'France — Le Havre',
    partnerType: 'PRIVATE_LABEL',
    containerQty: 1008,
    tcSize: 20,
    packing: '12×1L',
    volume: '1L',
    priceOnRequest: true,
    isOwnBrand: true,
  },
];

/** Carton-enriched product list. Single source of truth for consumers. */
export const ownProducts: Product[] = enrichProducts(ownProductsRaw);

/** Featured own-brand products — used by Home / FeaturedProducts. */
export const featuredOwnProducts = ownProducts.filter((p) => p.isFeatured);
