import type { Product } from '@/types';
import { enrichProducts } from '@/data/_generated/cartonsLoader';

import imgBlackTrain from '@/assets/products/spirits/black-train whiskey.jpg';
import imgBardinetSyrup from '@/assets/products/energy/bardinet-grenadine-syrup.webp';
import imgBulletEnergy from '@/assets/products/spirits/bullet-energy.webp';
import imgBulletVodka from '@/assets/products/spirits/bullet-vodka energy.webp';
import imgClassVodka from '@/assets/products/spirits/class-vodka-21-regular.png';
import imgCodysVodkaLemon from '@/assets/products/spirits/codys-vodka-lemon.png';
import imgCodysBeerExport from '@/assets/products/beer/codys-export.png';
import imgCuttySark from '@/assets/products/spirits/cutty-sark-scotch-whisky.webp';
import imgDivineApple from '@/assets/products/spirits/divine-apple-vodka.jpg';
import imgGinHarpon from '@/assets/products/spirits/Gin-Harpoon.jpg';
import imgIconicWhite from '@/assets/products/spirits/iconic-white-whiskey.webp';
import imgJackDa from '@/assets/products/spirits/jack-daniel.webp';
import imgJackDaHoney from '@/assets/products/spirits/jack-daniels-honey.jpg';
import imgLabel5 from '@/assets/products/spirits/label5-scotch-whisky.webp';
import imgNapoleonBrandy from '@/assets/products/spirits/napoleon_brandy_spirit_of_france_dubarry.jpg';
import imgOfficersChoice from '@/assets/products/spirits/officers-choice-prestige-whisky.jpg';
import ImgOldSoldier from '@/assets/products/spirits/old-soldier-whiskey.webp';
import imgPortoCruz from '@/assets/products/spirits/porto-cruz-rouge-tawny.jpg';
import imgRangerFine from '@/assets/products/spirits/fine-ranger-main.png';
import imgMangoustanRhum from '@/assets/products/spirits/rhum-mangoustans.jpg';
import imgRoyalStork from '@/assets/products/spirits/royal-stork-gin.jpg';
import imgSirEdouard from '@/assets/products/spirits/sir-edouard.jpeg';
import imgSpiritAfricanQueen from '@/assets/products/spirits/spirit-african-queen.jpg';
import imgSpiritHamwick from '@/assets/products/spirits/spirit-hamwick.jpg';
import imgSpiritNapoleon from '@/assets/products/spirits/spirit-napoleon.jpg';
import imgStjamesRhumAmber from '@/assets/products/spirits/st-james-rhum-amber.webp';
import imgTropicalVody from '@/assets/products/spirits/tropical-vody.png';
import imgVermouthRosso from '@/assets/products/spirits/black-train whiskey.jpg';
import imgWhiteBlueWhiskey from '@/assets/products/spirits/white-blue-whiskey.png';
import imgCodysEnergy from '@/assets/products/energy/codys-energy.png';
import imgCodysExtraStout from '@/assets/products/beer/codys-extra-stout.png';
import imgCodysBeerCitrus from '@/assets/products/beer/codys-beer-citrus-Vodka.png';
import imgBudweiser from '@/assets/products/beer/budweiser-glass.png';
import imgDesperados from '@/assets/products/beer/desperados-33-cl.jpg';
import imgBaronDarignac from '@/assets/products/wines/baron-darignac-rouge.jpg';
import imgBaronDeBalls from '@/assets/products/wines/baron-de-balls-vin-rouge-red-wine.webp';
import imgBaronDeValsRose from '@/assets/products/wines/baron-de-vals-rose.jpg';
import imgBaronRomeroSemiSweetRed from '@/assets/products/wines/baron-romero-semi-sweet-red.jpg';
import imgCastilloSanSimon from '@/assets/products/wines/castillo-san-simon-jumilla-red.png';
import imgChateauDuPoueyPetite from '@/assets/products/wines/chateau-du-pouey-Petite-vendange-rouge.webp';
import imgChateauHautBourbon from '@/assets/products/wines/Chateau-haut-bourbon.jpeg';
import imgChateauMarlene from '@/assets/products/wines/chateau-marlene-merlot.png';
import imgComteDechamberri from '@/assets/products/wines/comte-de chamberi-red.jpg';
import imgDonAntonio from '@/assets/products/wines/don-antonio-vin-rouge-75cl.jpg';
import imgEspumanteBaronDarignac from '@/assets/products/wines/espumante-baron-d-arignac-brut-blancs.jpg';
import imgFourCousinsNaturalSweetRose from '@/assets/products/wines/four-cousins-natural-sweet-rose.png';
import imgFourCousinsNaturalSweetWhite from '@/assets/products/wines/four-cousins-natural-sweet-white.webp';
import imgFourCousinsSweetRed from '@/assets/products/wines/four-cousins-sweet-red.jpg';
import imgJpChenetCabernet from '@/assets/products/wines/jp-chenet-cabernet-syrah.jpg';
import imgJpChenetIceEditionRose from '@/assets/products/wines/jp-chenet-ice-edition-rose.webp';
import imgJpChenetIceEdition from '@/assets/products/wines/jp-chenet-ice-edition.jpg';
import imgMunchoMasWhite from '@/assets/products/wines/mucho-mas-white.png';
import imgMunchoMasTinto from '@/assets/products/wines/mucho-mas-tinto black-edition.jpg';
import imgMuscadoreBlanc from '@/assets/products/wines/muscadore-blanc.jpg';
import imgMylowSparkling from '@/assets/products/wines/mylow-sparkling.webp';
import imgSangriaDonSimon from '@/assets/products/wines/sangria-don-simon-red.jpg';
import imgSparklingDonLucianoRose from '@/assets/products/wines/sparkling-don luciano-rose.jpg';
import imgVillaSofiaCabernet from '@/assets/products/wines/villa-sofia-cabernet-sauvignon.jpg';





// =====================================================================
// Partner brand SKUs — selected representative entries from the main
// "Diplo" sheet of the Excel master (claude/excel-data-dump.txt rows
// R2-R195) where partnerType ≠ PRIVATE_LABEL and supplier ≠ Vilniaus.
//
// Suppliers without a Diplo-known logo file (Bardinet, Felix solis,
// J. Garcia Carrion, etc.) are flagged as `partnerSlug: undefined` for
// now — Phase 2 will let the client confirm which fold under existing
// partner brands or get their own.  All entries set
// `isOwnBrand: false`, `priceOnRequest: true`.
// =====================================================================

function img(text: string, bg = '1E3A8A', fg = 'FCD34D'): string {
  return `https://placehold.co/800x600/${bg}/${fg}?text=${encodeURIComponent(text)}`;
}

// Raw catalog. `partnerProducts` (below) is enriched with carton specs.
const partnerProductsRaw: Product[] = [
  // ─── Cody's / Jens Warneke (Belgium) ─────────────────────────────
  {
    id: 'pp-codys-beer-citrus',
    slug: 'codys-beer-cirus-can',
    name: "Cody's Beer Citrus Can 5.4% — 24×33cl",
    code: '34-408',
    brand: "Cody's",
    description: "Cody's flagship 5.4% lager in 33cl can format — Belgian-brewed.",
    shortDescription: '5.4% Belgian lager — 33cl can.',
    categoryId: 'beer',
    image: imgCodysBeerCitrus,
    origin: 'Belgium — Antwerp',
    supplier: 'Jens Warneke',
    partnerType: 'PARTNER',
    partnerSlug: 'codys',
    isOwnBrand: false,
    containerQty: 2300,
    tcSize: 20,
    packing: '24×33cl',
    volume: '0.33L',
    alcoholContent: 5.4,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'pp-codys-citrus-vodka-beer',
    slug: 'codys-citrus-vodka-beer',
    name: "Cody's Citrus Vodka Beer 5.9% — 24×50cl",
    code: '34-413',
    brand: "Cody's",
    shortDescription: 'Citrus vodka beer hybrid — 5.9% ABV.',
    categoryId: 'beer',
    image: imgCodysVodkaLemon,
    origin: 'Belgium — Antwerp',
    supplier: 'Jens Warneke',
    partnerType: 'PARTNER',
    partnerSlug: 'codys',
    isOwnBrand: false,
    packing: '24×50cl',
    volume: '0.5L',
    alcoholContent: 5.9,
    priceOnRequest: true,
  },
  {
    id: 'pp-codys-energy-drink',
    slug: 'codys-energy-drink-25cl',
    name: "Cody's Energy Drink — 24×25cl",
    code: '34-402',
    brand: "Cody's",
    shortDescription: 'Cody-line energy drink — 25cl.',
    categoryId: 'energy-drink',
    image: imgCodysEnergy,
    origin: 'Belgium — Antwerp',
    supplier: 'Jens Warneke',
    partnerType: 'PARTNER',
    partnerSlug: 'codys',
    isOwnBrand: false,
    packing: '24×25cl',
    volume: '0.25L',
    priceOnRequest: true,
  },
  {
    id: 'pp-codys-vody-lemon',
    slug: 'codys-vody-lemon',
    name: "Cody's Vody Lemon 18% — 24×25cl",
    code: '34-422',
    brand: "Cody's",
    shortDescription: 'Lemon vodka mix — 18% ABV.',
    categoryId: 'vodka-mix',
    image: imgCodysVodkaLemon,
    origin: 'Belgium — Antwerp',
    supplier: 'Jens Warneke',
    partnerType: 'PARTNER',
    partnerSlug: 'codys',
    isOwnBrand: false,
    packing: '24×25cl',
    volume: '0.25L',
    alcoholContent: 18,
    priceOnRequest: true,
  },
  {
    id: 'pp-codys-tropical-vodka',
    slug: 'codys-tropical-vodka',
    name: "Cody's Tropical Vodka — 24×25cl",
    code: '34-420',
    brand: "Cody's",
    shortDescription: 'Tropical vodka mix — 18% ABV.',
    categoryId: 'vodka-mix',
    image: imgTropicalVody,
    origin: 'Belgium — Antwerp',
    supplier: 'Jens Warneke',
    partnerType: 'PARTNER',
    partnerSlug: 'codys',
    isOwnBrand: false,
    packing: '24×25cl',
    volume: '0.25L',
    alcoholContent: 18,
    priceOnRequest: true,
  },

  // ─── Lucas Bols ──────────────────────────────────────────────────
  {
    id: 'pp-royal-storck-gin',
    slug: 'royal-storck-gin',
    name: 'Gin Royal Storck — 6×75cl',
    code: '29-515',
    brand: 'Royal Storck',
    shortDescription: 'London gin — 6×75cl.',
    categoryId: 'gin',
    image: imgRoyalStork,
    origin: 'Belgium — Antwerp',
    supplier: 'Lucas Bols',
    partnerType: 'PARTNER',
    partnerSlug: 'lucas-bols',
    isOwnBrand: false,
    containerQty: 2260,
    tcSize: 20,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── Slaur Sardet ────────────────────────────────────────────────
  // {
  //   id: 'pp-bitter-viagali',
  //   slug: 'bitter-viagali',
  //   name: 'Bitter Viagali — 12×1L',
  //   code: '25-626',
  //   brand: 'Viagali',
  //   shortDescription: 'Italian-style bitter aperitif — 1L.',
  //   categoryId: 'bitters',
  //   image: img,
  //   origin: 'France — Le Havre',
  //   supplier: 'Slaur Sardet',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'slaur-sardet',
  //   isOwnBrand: false,
  //   containerQty: 1123,
  //   tcSize: 20,
  //   packing: '12×1L',
  //   volume: '1L',
  //   priceOnRequest: true,
  // },
  {
    id: 'pp-napoleon-brandy',
    slug: 'napoleon-sp-brandy',
    name: 'Napoleon SP Brandy — 6×70cl',
    code: '25-674',
    brand: 'Napoleon',
    shortDescription: 'Napoleon Special brandy.',
    categoryId: 'brandy',
    image: imgNapoleonBrandy,
    origin: 'France — Le Havre',
    supplier: 'Slaur Sardet',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'slaur-sardet',
    isOwnBrand: false,
    packing: '6×70cl',
    volume: '0.7L',
    priceOnRequest: true,
  },
  {
    id: 'pp-african-queen',
    slug: 'african-queen-chocolate',
    name: 'Spirit African Queen Chocolate 40% — 12×1L',
    code: '25-653',
    brand: 'African Queen',
    shortDescription: 'Chocolate cream liqueur — 40% ABV.',
    categoryId: 'liqueur',
    image: imgSpiritAfricanQueen,
    origin: 'France — Le Havre',
    supplier: 'Slaur Sardet',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'slaur-sardet',
    isOwnBrand: false,
    packing: '12×1L',
    volume: '1L',
    alcoholContent: 40,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'pp-gin-harpoon',
    slug: 'gin-harpoon',
    name: 'Gin Harpoon 40% — 12×100cl',
    code: '25-565',
    brand: 'Harpoon',
    shortDescription: 'French dry gin — 40% ABV, 1L.',
    categoryId: 'gin',
    image: imgGinHarpon,
    origin: 'France — Le Havre',
    supplier: 'Slaur Sardet',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'slaur-sardet',
    isOwnBrand: false,
    packing: '12×1L',
    volume: '1L',
    alcoholContent: 40,
    priceOnRequest: true,
  },
  {
    id: 'pp-rhum-mangoustan',
    slug: 'rhum-mangoustan-1l',
    name: 'Rhum Mangoustan 42% — 12×1L',
    code: '25-636',
    brand: 'Mangoustan',
    shortDescription: 'Premium 42% rum — 1L bottle.',
    categoryId: 'rum',
    image: imgMangoustanRhum,
    origin: 'France — Le Havre',
    supplier: 'Slaur Sardet',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'slaur-sardet',
    isOwnBrand: false,
    packing: '12×1L',
    volume: '1L',
    alcoholContent: 42,
    priceOnRequest: true,
    isFeatured: true,
  },
  // {
  //   id: 'pp-spirit-eperon',
  //   slug: 'spirit-eperon',
  //   name: 'Spirit Eperon — 12×100cl',
  //   code: '25-541',
  //   brand: 'Eperon',
  //   shortDescription: 'Whiskey-style spirit — 1L.',
  //   categoryId: 'whiskey',
  //   image: imgepero,
  //   origin: 'France — Le Havre',
  //   supplier: 'Slaur Sardet',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'slaur-sardet',
  //   isOwnBrand: false,
  //   packing: '12×1L',
  //   volume: '1L',
  //   priceOnRequest: true,
  // },
  {
    id: 'pp-spirit-hamwick',
    slug: 'spirit-hamwick',
    name: 'Spirit Hamwick 42% — 12×1L',
    code: '25-659',
    brand: 'Hamwick',
    shortDescription: 'Whiskey-style spirit — 42% ABV.',
    categoryId: 'whiskey',
    image: imgSpiritHamwick,
    origin: 'France — Le Havre',
    supplier: 'Slaur Sardet',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'slaur-sardet',
    isOwnBrand: false,
    packing: '12×1L',
    volume: '1L',
    alcoholContent: 42,
    priceOnRequest: true,
  },
  {
    id: 'pp-vermouth-fort-rosso',
    slug: 'vermouth-fort-rosso',
    name: 'Vermouth Fort Rosso 16% — 12×1L',
    code: '25-568',
    brand: 'Fort Rosso',
    shortDescription: 'Italian-style red vermouth — 16% ABV.',
    categoryId: 'liquor',
    image: imgVermouthRosso,
    origin: 'France — Le Havre',
    supplier: 'Slaur Sardet',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'slaur-sardet',
    isOwnBrand: false,
    packing: '12×1L',
    volume: '1L',
    alcoholContent: 16,
    priceOnRequest: true,
  },

  // ─── Allied Blenders & Distillers (India) ────────────────────────
  {
    id: 'pp-officers-choice',
    slug: 'officers-choice-whiskey',
    name: "Officer's Choice Whiskey — 12×75cl",
    code: '35-681',
    brand: "Officer's Choice",
    description: "India's iconic blended whiskey — Allied Blenders & Distillers flagship.",
    shortDescription: "India's iconic blended whiskey.",
    categoryId: 'whiskey',
    image: imgOfficersChoice,
    origin: 'India — Nhava Sheva',
    supplier: 'Allied Blenders and Distillers Ltd',
    partnerType: 'PARTNER',
    partnerSlug: 'allied-blenders-distillers',
    isOwnBrand: false,
    containerQty: 900,
    tcSize: 20,
    packing: '12×75cl',
    volume: '0.75L',
    priceOnRequest: true,
    isFeatured: true,
  },
  //{
  //   id: 'pp-officers-choice-blue',
  //   slug: 'officers-choice-blue',
  //   name: "Officer's Choice Blue — 12×75cl",
  //   code: '35-685',
  //   brand: "Officer's Choice",
  //   shortDescription: "Officer's Choice Blue label.",
  //   categoryId: 'whiskey',
  //   image: img("OFFICER'S\\nBLUE", '1E3A8A', 'FCD34D'),
  //   origin: 'India — Nhava Sheva',
  //   supplier: 'Allied Blenders and Distillers Ltd',
  //   partnerType: 'PARTNER',
  //   partnerSlug: 'allied-blenders-distillers',
  //   isOwnBrand: false,
  //   packing: '12×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },
  {
    id: 'pp-iconic-whiskey',
    slug: 'iconic-whiskey',
    name: 'Iconic Whiskey — 12×75cl',
    code: '35-684',
    brand: 'Iconic',
    shortDescription: 'Premium Indian blended whiskey.',
    categoryId: 'whiskey',
    image: imgIconicWhite,
    origin: 'India — Nhava Sheva',
    supplier: 'Allied Blenders and Distillers Ltd',
    partnerType: 'PARTNER',
    partnerSlug: 'allied-blenders-distillers',
    isOwnBrand: false,
    packing: '12×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-class-21',
    slug: 'class-21-vodka',
    name: 'Class 21 Vodka — 12×1L',
    code: '35-686',
    brand: 'Class 21',
    shortDescription: 'Premium Indian vodka — 1L.',
    categoryId: 'vodka',
    image: imgClassVodka,
    origin: 'India — Nhava Sheva',
    supplier: 'Allied Blenders and Distillers Ltd',
    partnerType: 'PARTNER',
    partnerSlug: 'allied-blenders-distillers',
    isOwnBrand: false,
    packing: '12×1L',
    volume: '1L',
    priceOnRequest: true,
  },
  // {
  //   id: 'pp-officers-cafe-rum',
  //   slug: 'officers-choice-cafe-rum',
  //   name: "Officer's Choice Café Rum — 12×75cl",
  //   code: '35-682',
  //   brand: "Officer's Choice",
  //   shortDescription: 'Coffee-flavoured rum.',
  //   categoryId: 'rum',
  //   subCategoryId: 'cafe',
  //   image: img("OFFICER'S\\nCAFE RUM", '4A2C1A', 'FCD34D'),
  //   origin: 'India — Nhava Sheva',
  //   supplier: 'Allied Blenders and Distillers Ltd',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'allied-blenders-distillers',
  //   isOwnBrand: false,
  //   packing: '12×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },

  // ─── Alcobrew ───────────────────────────────────────────────────
  {
    id: 'pp-white-blue-premium',
    slug: 'white-and-blue-premium-whisky',
    name: 'White & Blue Premium Whisky — 12×75cl',
    code: '39-699',
    brand: 'White & Blue',
    shortDescription: 'Premium Indian whisky with glass — gift-pack carton.',
    categoryId: 'whiskey',
    image: imgWhiteBlueWhiskey,
    origin: 'India — Mundra',
    supplier: 'Alcobrew Distilleries',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'alcobrew',
    isOwnBrand: false,
    containerQty: 1601,
    tcSize: 40,
    packing: '12×75cl',
    volume: '0.75L',
    priceOnRequest: true,
    isFeatured: true,
  },
  // {
  //   id: 'pp-white-blue-reserve',
  //   slug: 'white-and-blue-reserve',
  //   name: 'White & Blue Reserve — 12×750ml',
  //   code: '39-719',
  //   brand: 'White & Blue',
  //   shortDescription: 'Reserve blend with canister.',
  //   categoryId: 'whiskey',
  //   image: img('WHITE & BLUE\\nRESERVE', '0F172A', 'F8FAFC'),
  //   origin: 'India — Mundra',
  //   supplier: 'Alcobrew Distilleries',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'alcobrew',
  //   isOwnBrand: false,
  //   packing: '12×750ml',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },

  // ─── Blue Ocean Beverages ────────────────────────────────────────
  {
    id: 'pp-old-soldier',
    slug: 'old-soldier-whisky',
    name: 'Old Soldier Whisky — 12×75cl',
    code: '16-221',
    brand: 'Old Soldier',
    shortDescription: 'Indian blended whisky.',
    categoryId: 'whiskey',
    image: ImgOldSoldier,
    origin: 'India — Jawaharlal Nehru',
    supplier: 'Blue Ocean Beverages',
    partnerType: 'PARTNER',
    partnerSlug: 'blue-ocean-beverages',
    isOwnBrand: false,
    containerQty: 1325,
    tcSize: 20,
    packing: '12×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-ranger-fine',
    slug: 'ranger-fine-whisky',
    name: 'Ranger Fine Special Blend Whisky — 12×1000ml',
    code: '16-236',
    brand: 'Ranger',
    shortDescription: 'Special blended Indian whisky.',
    categoryId: 'whiskey',
    image: imgRangerFine,
    origin: 'India — Jawaharlal Nehru',
    supplier: 'Blue Ocean Beverages',
    partnerType: 'PARTNER',
    partnerSlug: 'blue-ocean-beverages',
    isOwnBrand: false,
    packing: '12×1L',
    volume: '1L',
    priceOnRequest: true,
  },

  // ─── Groupe GCF (France) ─────────────────────────────────────────
  {
    id: 'pp-jp-chenet-cab-syrah',
    slug: 'jp-chenet-cabernet-syrah',
    name: 'JP Chenet Cabernet Syrah Pays D\'Oc — 6×75cl',
    code: '26-049',
    brand: 'JP Chenet',
    shortDescription: 'Iconic French Cabernet Syrah blend.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgJpChenetCabernet,
    origin: 'France — Le Havre',
    supplier: 'Grands Chais De France',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'groupe-gcf',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'pp-jp-chenet-ice-rose',
    slug: 'jp-chenet-ice-rose',
    name: 'JP Chenet Ice Edition Rosé — 6×75cl',
    code: '26-731',
    brand: 'JP Chenet',
    shortDescription: 'Sparkling Ice Edition rosé.',
    categoryId: 'wine',
    subCategoryId: 'sparkling',
    image: imgJpChenetIceEditionRose,
    origin: 'France — Le Havre',
    supplier: 'Grands Chais De France',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'groupe-gcf',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  // {
  //   id: 'pp-jp-chenet-fashion-cassis',
  //   slug: 'jp-chenet-fashion-cassis',
  //   name: 'JP Chenet Fashion Cassis 8% — 6×75cl',
  //   code: '27-565',
  //   brand: 'JP Chenet',
  //   shortDescription: 'Cassis-flavoured sparkling wine — 8% ABV.',
  //   categoryId: 'wine',
  //   subCategoryId: 'sparkling',
  //   image: img('JP CHENET\\nCASSIS', '4C1D95', 'FCD34D'),
  //   origin: 'France — Le Havre',
  //   supplier: 'Grands Chais De France',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'groupe-gcf',
  //   isOwnBrand: false,
  //   packing: '6×75cl',
  //   volume: '0.75L',
  //   alcoholContent: 8,
  //   priceOnRequest: true,
  // },
  {
    id: 'pp-baron-darignac-red',
    slug: 'baron-darignac-medium-sweet-red',
    name: "Baron D'arignac Medium Sweet Red — 6×75cl",
    code: '26-737',
    brand: "Baron D'arignac",
    shortDescription: 'Medium-sweet French red.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgBaronDarignac,
    origin: 'France — Le Havre',
    supplier: 'Grands Chais De France',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'groupe-gcf',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  // {
  //   id: 'pp-baron-darignac-brut',
  //   slug: 'baron-darignac-sparkling-brut',
  //   name: "Baron D'arignac Sparkling Brut — 6×75cl",
  //   code: '26-770',
  //   brand: "Baron D'arignac",
  //   shortDescription: 'Sparkling brut white.',
  //   categoryId: 'wine',
  //   subCategoryId: 'sparkling',
  //   image: imgbaro,
  //   origin: 'France — Le Havre',
  //   supplier: 'Grands Chais De France',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'groupe-gcf',
  //   isOwnBrand: false,
  //   packing: '6×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },
  {
    id: 'pp-jack-daniels-3l',
    slug: 'jack-daniels-3l',
    name: "Jack Daniel's 3L",
    code: '26-085',
    brand: "Jack Daniel's",
    shortDescription: 'Tennessee whiskey — 3L magnum.',
    categoryId: 'whiskey',
    image: imgJackDa,
    origin: 'France — Le Havre',
    supplier: 'Grands Chais De France',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'groupe-gcf',
    isOwnBrand: false,
    packing: '3L',
    volume: '3L',
    priceOnRequest: true,
  },
  {
    id: 'pp-jack-honey',
    slug: 'jack-honey-70cl',
    name: 'Jack Honey — 6×0.70cl',
    code: '26-668',
    brand: "Jack Daniel's",
    shortDescription: 'Honey-finished Tennessee whiskey.',
    categoryId: 'whiskey',
    image: imgJackDaHoney,
    origin: 'France — Le Havre',
    supplier: 'Grands Chais De France',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'groupe-gcf',
    isOwnBrand: false,
    packing: '6×70cl',
    volume: '0.7L',
    priceOnRequest: true,
  },
  {
    id: 'pp-divine-apple-vodka',
    slug: 'divine-apple-vodka',
    name: 'Divine Apple Vodka — 6×70cl',
    code: '27-562',
    brand: 'Divine',
    shortDescription: 'Apple-flavoured vodka.',
    categoryId: 'vodka',
    image: imgDivineApple,
    origin: 'France — Le Havre',
    supplier: 'Grands Chais De France',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'groupe-gcf',
    isOwnBrand: false,
    packing: '6×70cl',
    volume: '0.7L',
    priceOnRequest: true,
  },

  // ─── CFGV (Compagnie Française des Grands Vins) ──────────────────
  {
    id: 'pp-muscador-blanc',
    slug: 'muscador-blanc',
    name: 'Muscador 100% Blanc — 6×75cl',
    code: '11-852',
    brand: 'Muscador',
    shortDescription: 'Sparkling white Muscador.',
    categoryId: 'wine',
    subCategoryId: 'sparkling',
    image: imgMuscadoreBlanc,
    origin: 'France — Le Havre',
    supplier: 'CFGV',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'compagnie-francaise-grands-vins',
    isOwnBrand: false,
    containerQty: 2092,
    tcSize: 20,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  // {
  //   id: 'pp-muscador-rose',
  //   slug: 'muscador-rose',
  //   name: 'Muscador 100% Rose — 6×75cl',
  //   code: '11-851',
  //   brand: 'Muscador',
  //   shortDescription: 'Sparkling rosé Muscador.',
  //   categoryId: 'wine',
  //   subCategoryId: 'sparkling',
  //   image: img('MUSCADOR\\nROSE', 'F472B6', 'FCD34D'),
  //   origin: 'France — Le Havre',
  //   supplier: 'CFGV',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'compagnie-francaise-grands-vins',
  //   isOwnBrand: false,
  //   packing: '6×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },
  {
    id: 'pp-mylow',
    slug: 'mylow-blanc',
    name: 'MYLOW Boisson 6.7% Blanc — 6×0.75cl',
    code: '11-930',
    brand: 'MYLOW',
    shortDescription: 'Sparkling white drink — 6.7% ABV.',
    categoryId: 'wine',
    subCategoryId: 'sparkling',
    image: imgMylowSparkling,
    origin: 'France — Le Havre',
    supplier: 'CFGV',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'compagnie-francaise-grands-vins',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 6.7,
    priceOnRequest: true,
  },

  // ─── Antonio Arraez ──────────────────────────────────────────────
  // {
  //   id: 'pp-baron-del-lugar',
  //   slug: 'baron-del-lugar-red',
  //   name: 'Baron del Lugar Red — 6×75cl',
  //   code: '14-781',
  //   brand: 'Baron del Lugar',
  //   shortDescription: 'Spanish red wine — 6×75cl.',
  //   categoryId: 'wine',
  //   subCategoryId: 'red',
  //   image: img('BARON\\nDEL LUGAR', '7F1D1D', 'FCD34D'),
  //   origin: 'Spain — Valencia',
  //   supplier: 'Antonio Arraez',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'arraez-1934',
  //   isOwnBrand: false,
  //   containerQty: 2474,
  //   tcSize: 20,
  //   packing: '6×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },
  {
    id: 'pp-don-antonio',
    slug: 'don-antonio-rouge',
    name: 'Don Antonio Rouge — 75cl',
    code: '14-794',
    brand: 'Don Antonio',
    shortDescription: 'Spanish red wine.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgDonAntonio,
    origin: 'Spain — Valencia',
    supplier: 'Antonio Arraez',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'arraez-1934',
    isOwnBrand: false,
    packing: '75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  // {
  //   id: 'pp-petite-vendange',
  //   slug: 'petite-vendange-red',
  //   name: 'Petite Vendange Red Wine — 75cl',
  //   code: '14-792',
  //   brand: 'Petite Vendange',
  //   shortDescription: 'Spanish red — 75cl.',
  //   categoryId: 'wine',
  //   subCategoryId: 'red',
  //   image: img('PETITE\\nVENDANGE', '7F1D1D', 'FCD34D'),
  //   origin: 'Spain — Valencia',
  //   supplier: 'Antonio Arraez',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   partnerSlug: 'arraez-1934',
  //   isOwnBrand: false,
  //   packing: '75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },

  // ─── Four Cousins (Van Loveren) ──────────────────────────────────
  {
    id: 'pp-four-cousins-red',
    slug: 'four-cousins-natural-sweet-red',
    name: 'Four Cousins Natural Sweet Red — 12×750ml',
    code: '38-408',
    brand: 'Four Cousins',
    description: 'South Africa\'s top-selling natural sweet red — Van Loveren family wine.',
    shortDescription: 'Natural Sweet Red — 750ml.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgFourCousinsSweetRed,
    origin: 'South Africa — Cape Town',
    supplier: 'Van Loveren',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'four-cousins',
    isOwnBrand: false,
    containerQty: 1350,
    tcSize: 20,
    packing: '12×750ml',
    volume: '0.75L',
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'pp-four-cousins-rose',
    slug: 'four-cousins-natural-sweet-rose',
    name: 'Four Cousins Natural Sweet Rose — 12×750ml',
    code: '38-406',
    brand: 'Four Cousins',
    shortDescription: 'Natural Sweet Rose.',
    categoryId: 'wine',
    subCategoryId: 'rose',
    image: imgFourCousinsNaturalSweetRose,
    origin: 'South Africa — Cape Town',
    supplier: 'Van Loveren',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'four-cousins',
    isOwnBrand: false,
    packing: '12×750ml',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-four-cousins-white',
    slug: 'four-cousins-natural-sweet-white',
    name: 'Four Cousins Natural Sweet White — 12×750ml',
    code: '38-407',
    brand: 'Four Cousins',
    shortDescription: 'Natural Sweet White.',
    categoryId: 'wine',
    subCategoryId: 'white',
    image: imgFourCousinsNaturalSweetWhite,
    origin: 'South Africa — Cape Town',
    supplier: 'Van Loveren',
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: 'four-cousins',
    isOwnBrand: false,
    packing: '12×750ml',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── Bardinet (no logo / TODO mapping) ───────────────────────────
  {
    id: 'pp-cutty-sark',
    slug: 'cutty-sark-scotch-whisky',
    name: 'Cutty Sark Scotch Whisky 40% — 12×70cl',
    code: '35-677',
    brand: 'Cutty Sark',
    shortDescription: 'Scotch whisky — 40% ABV.',
    categoryId: 'whiskey',
    image: imgCuttySark,
    origin: 'France — Le Havre',
    supplier: 'Bardinet', // TODO: confirm partner slug — possibly La Martiniquaise
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '12×70cl',
    volume: '0.7L',
    alcoholContent: 40,
    priceOnRequest: true,
  },
  {
    id: 'pp-label-5',
    slug: 'label-5-scotch-whisky',
    name: 'Label 5 Scotch Whisky — 12×70cl ETUI',
    code: '80-579',
    brand: 'Label 5',
    shortDescription: 'Scotch whisky — gift carton.',
    categoryId: 'whiskey',
    image: imgLabel5,
    origin: 'France — Le Havre',
    supplier: 'Bardinet',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '12×70cl',
    volume: '0.7L',
    priceOnRequest: true,
  },
  {
    id: 'pp-sir-edouard',
    slug: 'sir-edouard-2l',
    name: 'Sir Edouard 2L — 6-pack',
    code: '81-481',
    brand: 'Sir Edouard',
    shortDescription: 'Whiskey 2L family bottle.',
    categoryId: 'whiskey',
    image: imgSirEdouard,
    origin: 'France — Le Havre',
    supplier: 'Bardinet',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×2L',
    volume: '2L',
    priceOnRequest: true,
  },
  {
    id: 'pp-bardinet-grenadine',
    slug: 'bardinet-grenadine-syrup',
    name: 'Bardinet Grenadine Syrup — 6×1L',
    code: '81-484',
    brand: 'Bardinet',
    shortDescription: 'Grenadine syrup — 1L bottles.',
    categoryId: 'sauces',
    image: imgBardinetSyrup,
    origin: 'France — Le Havre',
    supplier: 'Bardinet',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×1L',
    volume: '1L',
    priceOnRequest: true,
  },
  {
    id: 'pp-old-nick-white-rum',
    slug: 'old-nick-white-rum',
    name: 'Old Nick White Rum 37.5% — 6×70cl',
    code: '35-678',
    brand: 'Old Nick',
    shortDescription: 'White rum — 37.5% ABV.',
    categoryId: 'rum',
    subCategoryId: 'white',
    image: ImgOldSoldier,
    origin: 'France — Le Havre',
    supplier: 'Bardinet',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×70cl',
    volume: '0.7L',
    alcoholContent: 37.5,
    priceOnRequest: true,
  },
  {
    id: 'pp-st-james-amber',
    slug: 'st-james-rhum-amber',
    name: 'St James Rhum Amber — 6×1L',
    code: '26-565',
    brand: 'St James',
    shortDescription: 'Amber rum with glass — 1L.',
    categoryId: 'rum',
    subCategoryId: 'amber',
    image: imgStjamesRhumAmber,
    origin: 'France — Le Havre',
    supplier: 'Bardinet',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×1L',
    volume: '1L',
    priceOnRequest: true,
  },
  {
    id: 'pp-porto-cruz',
    slug: 'porto-cruz-rouge',
    name: 'Porto Cruz Rouge / Tawny — 6×75cl',
    code: '25-956',
    brand: 'Porto Cruz',
    shortDescription: 'Portuguese tawny port.',
    categoryId: 'wine',
    subCategoryId: 'porto',
    image: imgPortoCruz,
    origin: 'France — Le Havre',
    supplier: 'Bardinet',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── Felix Solis (Spain) — TODO partner mapping ──────────────────
  {
    id: 'pp-mucho-mas-tinto',
    slug: 'mucho-mas-tinto',
    name: 'Mucho Mas Tinto Black Edition — 6×75cl',
    code: '19-944',
    brand: 'Mucho Mas',
    shortDescription: 'Spanish red — black edition.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgMunchoMasTinto,
    origin: 'Spain — Valencia',
    supplier: 'Felix Solis', // TODO: confirm partner slug
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-mucho-mas-white',
    slug: 'mucho-mas-white',
    name: 'Mucho Mas White — 6×75cl',
    code: '19-948',
    brand: 'Mucho Mas',
    shortDescription: 'Spanish white — black edition.',
    categoryId: 'wine',
    subCategoryId: 'white',
    image: imgMunchoMasWhite,
    origin: 'Spain — Valencia',
    supplier: 'Felix Solis',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-comte-de-chamberi',
    slug: 'comte-de-chamberi-red',
    name: 'Comte de Chamberi Red — 6×75cl',
    code: '17-278',
    brand: 'Comte de Chamberi',
    shortDescription: 'Spanish red.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgComteDechamberri,
    origin: 'Spain — Valencia',
    supplier: 'Felix Solis',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── J. García Carrión (Spain) — TODO mapping ────────────────────
  {
    id: 'pp-don-simon-red',
    slug: 'sangria-don-simon-red-1-5l',
    name: 'Sangria Don Simon Red 1.5L Glass — 6-pack',
    code: '17-069',
    brand: 'Don Simon',
    shortDescription: 'Spanish sangria — 1.5L glass.',
    categoryId: 'wine',
    subCategoryId: 'sangria',
    image: imgSangriaDonSimon,
    origin: 'Spain — Valencia',
    supplier: 'J. García Carrión',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×1.5L',
    volume: '1.5L',
    priceOnRequest: true,
  },
  {
    id: 'pp-castillo-san-simon-red',
    slug: 'castillo-san-simon-red',
    name: 'Castillo San Simon Jumilla Red — 6×75cl',
    code: '17-066',
    brand: 'Castillo San Simon',
    shortDescription: 'Spanish red — Jumilla DO.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgCastilloSanSimon,
    origin: 'Spain — Valencia',
    supplier: 'J. García Carrión',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-baron-romero-red',
    slug: 'baron-romero-semi-sweet-red',
    name: 'Baron Romero Semi Sweet Red — 6×75cl',
    code: '17-064',
    brand: 'Baron Romero',
    shortDescription: 'Semi-sweet Spanish red.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgBaronRomeroSemiSweetRed,
    origin: 'Spain — Valencia',
    supplier: 'J. García Carrión',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-don-luciano-rose',
    slug: 'sparkling-don-luciano-rose',
    name: 'Sparkling Don Luciano Rose — 75cl',
    code: '22-652',
    brand: 'Don Luciano',
    shortDescription: 'Sparkling rosé.',
    categoryId: 'wine',
    subCategoryId: 'sparkling',
    image: imgSparklingDonLucianoRose,
    origin: 'Spain — Valencia',
    supplier: 'J. García Carrión',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── Vicente Gandía ──────────────────────────────────────────────
  {
    id: 'pp-baron-de-vals-rouge',
    slug: 'baron-de-vals-rouge',
    name: 'Baron De Vals Rouge — 6×75cl',
    code: '21-460',
    brand: 'Baron De Vals',
    shortDescription: 'Spanish red.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgBaronDeBalls,
    origin: 'Spain — Valencia',
    supplier: 'Vicente Gandía',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },
  {
    id: 'pp-baron-de-vals-rose',
    slug: 'baron-de-vals-rose',
    name: 'Baron De Vals Rose — 6×75cl',
    code: '21-461',
    brand: 'Baron De Vals',
    shortDescription: 'Spanish rosé.',
    categoryId: 'wine',
    subCategoryId: 'rose',
    image: imgBaronDeValsRose,
    origin: 'Spain — Valencia',
    supplier: 'Vicente Gandía',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── Vinomania (Bulgaria) ────────────────────────────────────────
  {
    id: 'pp-villa-sofia-cab-sauvignon',
    slug: 'villa-sofia-cabernet-sauvignon',
    name: 'Villa Sofia Cabernet Sauvignon 14% — 6×75cl',
    code: '37-573',
    brand: 'Villa Sofia',
    shortDescription: 'Bulgarian Cabernet Sauvignon — 14% ABV.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgVillaSofiaCabernet,
    origin: 'Bulgaria — Burgas',
    supplier: 'Vinomania Food (BWC)',
    partnerType: 'EXCLUSIVE_PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    alcoholContent: 14,
    priceOnRequest: true,
  },
  {
    id: 'pp-chateau-marlene-merlot',
    slug: 'chateau-marlene-merlot',
    name: 'Chateau Marlene Merlot — 6×75cl',
    code: '37-560',
    brand: 'Chateau Marlene',
    shortDescription: 'Bulgarian Merlot.',
    categoryId: 'wine',
    subCategoryId: 'red',
    image: imgChateauMarlene,
    origin: 'Bulgaria — Burgas',
    supplier: 'Vinomania Food (BWC)',
    partnerType: 'EXCLUSIVE_PARTNER',
    isOwnBrand: false,
    packing: '6×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── La Cave Des Rois (Romania) ──────────────────────────────────
  // {
  //   id: 'pp-nuits-des-anges-rose',
  //   slug: 'nuits-des-anges-rose',
  //   name: 'Nuits des Anges Cote de Provence Rose — 6×75cl',
  //   code: '30-372',
  //   brand: 'Nuits des Anges',
  //   shortDescription: 'Provence-style rose.',
  //   categoryId: 'wine',
  //   subCategoryId: 'rose',
  //   image: img('NUITS\\nDES ANGES', 'F472B6', 'FCD34D'),
  //   origin: 'Romania — Constanta',
  //   supplier: 'La Cave Des Rois SAL',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   isOwnBrand: false,
  //   packing: '6×75cl',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },

  // ─── enJOYbev (Belgium) ──────────────────────────────────────────
  {
    id: 'pp-bullet-vodka-energy',
    slug: 'bullet-vodka-energy',
    name: 'Bullet Vodka Energy — 24×25cl',
    code: '30-241',
    brand: 'Bullet',
    shortDescription: 'Vodka energy mix — no taurine, no caffeine.',
    categoryId: 'vodka-mix',
    image: imgBulletEnergy,
    origin: 'Belgium — Antwerp',
    supplier: 'enJOYbev FZE',
    partnerType: 'EXCLUSIVE_PARTNER',
    isOwnBrand: false,
    packing: '24×25cl',
    volume: '0.25L',
    priceOnRequest: true,
  },

  // ─── Sun Mark / Gentrax — international beer & energy ───────────
  {
    id: 'pp-budweiser-glass',
    slug: 'budweiser-glass-33cl',
    name: 'Budweiser Glass — 24×33cl',
    code: '16-281',
    brand: 'Budweiser',
    shortDescription: 'Budweiser lager.',
    categoryId: 'beer',
    image: imgBudweiser,
    origin: 'Netherlands — Rotterdam',
    supplier: 'Gentrax International',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    containerQty: 1600,
    tcSize: 40,
    packing: '24×33cl',
    volume: '0.33L',
    priceOnRequest: true,
  },
  {
    id: 'pp-desperados',
    slug: 'desperados-33cl',
    name: 'Desperados — 24×33cl',
    code: '36-830',
    brand: 'Desperados',
    shortDescription: 'Tequila-flavoured lager.',
    categoryId: 'beer',
    image: imgDesperados,
    origin: 'Netherlands — Rotterdam',
    supplier: 'Gentrax International',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '24×33cl',
    volume: '0.33L',
    priceOnRequest: true,
  },
  {
    id: 'pp-bullet-energy-25',
    slug: 'bullet-energy-25cl',
    name: 'Bullet Energy — 24×25cl',
    code: '22-879',
    brand: 'Bullet',
    shortDescription: 'Energy drink — 25cl.',
    categoryId: 'energy-drink',
    image: imgBulletEnergy,
    origin: 'Belgium — Antwerp',
    supplier: 'Sun Mark Limited',
    partnerType: 'EXCLUSIVE_PARTNER',
    isOwnBrand: false,
    packing: '24×25cl',
    volume: '0.25L',
    priceOnRequest: true,
  },

  // ─── MALCO Trading (India) ───────────────────────────────────────
  {
    id: 'pp-black-train',
    slug: 'black-train-whiskey',
    name: 'Black Train Whiskey — 12×75cl',
    code: '37-542',
    brand: 'Black Train',
    shortDescription: 'Indian blended whiskey.',
    categoryId: 'whiskey',
    image: imgBlackTrain,
    origin: 'India — Chennai',
    supplier: 'MALCO Trading',
    partnerType: 'PARTNER',
    isOwnBrand: false,
    packing: '12×75cl',
    volume: '0.75L',
    priceOnRequest: true,
  },

  // ─── Manas Agro (India) — Kaptaan / Wolf Stone (note: also some
  //     PRIVATE LABEL Kaaptan variants live in ownProducts.ts) ──────
  // {
  //   id: 'pp-wolfstone-prem',
  //   slug: 'wolf-stone-premium',
  //   name: 'The Wolf Stone Premium Whiskey — 12×750ml',
  //   code: '38-754',
  //   brand: 'Wolf Stone',
  //   shortDescription: 'Premium Indian whiskey, mono-carton.',
  //   categoryId: 'whiskey',
  //   image: imgwolf,
  //   origin: 'India — Nhava Sheva',
  //   supplier: 'Manas Agro Industries',
  //   partnerType: 'EXCLUSIVE_PARTNER',
  //   isOwnBrand: false,
  //   packing: '12×750ml',
  //   volume: '0.75L',
  //   priceOnRequest: true,
  // },

  // ─── La Sénégalaise de Boissons ──────────────────────────────────
  // {
  //   id: 'pp-el-passo-sangria',
  //   slug: 'el-passo-sangria',
  //   name: 'El Passo Sangria 18% — 24×250cl',
  //   code: '22-900',
  //   brand: 'El Passo',
  //   shortDescription: 'Senegal-bottled sangria — 18% ABV.',
  //   categoryId: 'wine',
  //   subCategoryId: 'sangria',
  //   image: img('EL PASSO\\nSANGRIA', 'F87171', 'FCD34D'),
  //   origin: 'Senegal — Dakar',
  //   supplier: 'La Sénégalaise de Boissons',
  //   partnerType: 'PARTNER',
  //   isOwnBrand: false,
  //   packing: '24×250cl',
  //   alcoholContent: 18,
  //   priceOnRequest: true,
  // },
];

/** Carton-enriched. Single source of truth for partner products. */
export const partnerProducts: Product[] = enrichProducts(partnerProductsRaw);

export const featuredPartnerProducts = partnerProducts.filter((p) => p.isFeatured);
