import type { Product } from '@/types';
import { enrichProducts } from '@/data/_generated/cartonsLoader';

// Real product photography for the Vilniaus Degtine range. Sourced
// from supplier materials. Vite resolves these to hashed asset URLs.
import imgGalipoteDark from '@/assets/products/spirits/vilniaus/el-galipote-dark-rum.jpg';
import imgGalipoteSpiced from '@/assets/products/spirits/vilniaus/el-galipote-spiced.jpg';
import imgGalipotePinkCherry from '@/assets/products/spirits/vilniaus/el-galipote-pink-cherry.jpg';
import imgGalipoteBlackSpiced from '@/assets/products/spirits/vilniaus/el-Galipote-black-spiced.jpg';
import imgGalipotePineapple from '@/assets/products/spirits/vilniaus/el-galipote-pineapple.png';


import imgGalipoteCoconut from '@/assets/products/spirits/vilniaus/el-galipote-coconut.jpg';
import imgGalipoteBlackCurrant from '@/assets/products/spirits/vilniaus/barska-blackcurrant.png';

import imgThornGin from '@/assets/products/spirits/vilniaus/thorn-gin.jpg';
import imgThornPinkGin from '@/assets/products/spirits/vilniaus/thorn-pink-gin.jpg';
import imgObeliuCrafted from '@/assets/products/spirits/vilniaus/obeliu-crafted-vodka.png';
import img7SensesNuts from '@/assets/products/spirits/vilniaus/seven-senses-nuts.jpg';
import img7SensesHerbal from '@/assets/products/spirits/vilniaus/seven-senses-herbal.jpg';
import imgBarskaPremium from '@/assets/products/spirits/vilniaus/barska-premium-vodka.jpg';
import imgBarskaClassic from '@/assets/products/spirits/vilniaus/barska-classic-vodka.png';
import imgBarskaQuince from '@/assets/products/spirits/vilniaus/barska-quince-front-0.7L.png';

import imgBarskaClassic200 from '@/assets/products/spirits/vilniaus/barska-classic-200ml.jpg';
import imgBarskaPlum from '@/assets/products/spirits/vilniaus/barska-plum.png';
import imgBarskaCranberry from '@/assets/products/spirits/vilniaus/barska-cranberry.png';
import imgBarskaLemon from '@/assets/products/spirits/vilniaus/barska-lemon.jpg';
import imgAdmiralVodka from '@/assets/products/spirits/vilniaus/admiral-vodka.jpg';
import imgAdmiralGin from '@/assets/products/spirits/vilniaus/admiral-gin.jpg';
import imgMissedCallDryGin from '@/assets/products/spirits/vilniaus/missed-call london-dry-gin-.png';
import imgMissedCallStrawberryGin from '@/assets/products/spirits/vilniaus/missed-call-strawberry-gin.png';
import imgCepkeliaiCraneBerry from '@/assets/products/spirits/vilniaus/cepkeliu-misko uogu-trauktine.png';
import imgCepkeliaiForestberry from '@/assets/products/spirits/vilniaus/cepkeliu-spanguoliu-trauktine.png';
import imgCepkeliaiCowberry from '@/assets/products/spirits/vilniaus/cepkeliai-cowberry.jpg';


// =====================================================================
// Vilniaus Degtinė full SKU list — sourced from the "vilinaus" sheet
// (rows R5-R61) of the Excel master. Includes EAN codes, MOQ, lead time,
// alcohol %, volume.  Every entry is `partnerSlug: 'vilniaus-degtine'`,
// `partnerType: 'EXCLUSIVE_PARTNER'`, `isOwnBrand: false`.
// =====================================================================

function img(text: string, bg = '0F172A', fg = 'FCD34D'): string {
  return `https://placehold.co/800x600/${bg}/${fg}?text=${encodeURIComponent(text)}`;
}

const PARTNER = 'vilniaus-degtine';
const SUPPLIER = 'Vilniaus Degtinė, UAB';

// Raw catalog. `vilniausProducts` (below) is enriched with manufacturer
// pallet/truck stats from `cartons-vilniaus.json` (the richest source).
const vilniausProductsRaw: Product[] = [
  // ─── El Galipote (Rum / Spirit drinks) ──────────────────────────
  {
    id: 'vd-galipote-dark',
    slug: 'el-galipote-dark-rum',
    name: 'El Galipote Dark Rum',
    brand: 'El Galipote',
    description: 'Dominican Republic dark rum — 40% ABV, 0.7L. Distilled in the Caribbean, bottled in Lithuania for Diplo.',
    shortDescription: 'Dominican dark rum — 40% ABV.',
    categoryId: 'rum',
    subCategoryId: 'dark',
    image: imgGalipoteDark,
    origin: 'Dominican Republic',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 40,
    ean: '4770053240659',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'vd-galipote-white',
    slug: 'el-galipote-white-rum',
    name: 'El Galipote White Rum',
    brand: 'El Galipote',
    shortDescription: 'Dominican white rum — 37.5% ABV.',
    categoryId: 'rum',
    subCategoryId: 'white',
    image: imgGalipoteDark, // TODO: client to provide white rum image
    origin: 'Dominican Republic',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 37.5,
    ean: '4770053240635',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-galipote-spiced',
    slug: 'el-galipote-spiced',
    name: 'El Galipote Spiced Spirit Drink',
    brand: 'El Galipote',
    shortDescription: 'Spiced Caribbean-style spirit — 35% ABV.',
    categoryId: 'spirit-drink',
    subCategoryId: 'spiced',
    image: imgGalipoteSpiced,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 35,
    ean: '4770053240819',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-galipote-pineapple',
    slug: 'el-galipote-pineapple',
    name: 'El Galipote Pineapple Spirit Drink',
    brand: 'El Galipote',
    shortDescription: 'Pineapple spirit drink — 35% ABV.',
    categoryId: 'spirit-drink',
    image: imgGalipotePineapple,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 35,
    ean: '4770053241533',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-galipote-black-spiced',
    slug: 'el-galipote-black-spiced',
    name: 'El Galipote Black Spiced (NEW)',
    brand: 'El Galipote',
    shortDescription: 'New black-spiced expression — 35% ABV.',
    categoryId: 'spirit-drink',
    image: imgGalipoteBlackSpiced,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 35,
    ean: '4770053242592',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'vd-galipote-pink-cherry',
    slug: 'el-galipote-pink-cherry',
    name: 'El Galipote Pink Cherry Spirit Drink',
    brand: 'El Galipote',
    shortDescription: 'Pink cherry spirit drink — 35% ABV.',
    categoryId: 'spirit-drink',
    image: imgGalipotePinkCherry,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 35,
    ean: '4770053242479',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-galipote-coconut',
    slug: 'el-galipote-coconut-liqueur',
    name: 'El Galipote Coconut Liqueur',
    brand: 'El Galipote',
    shortDescription: 'Coconut cream liqueur — 17% ABV.',
    categoryId: 'liqueur',
    image: imgGalipoteCoconut,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 17,
    ean: '4770053241601',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Thorn Gin ──────────────────────────────────────────────────
  {
    id: 'vd-thorn-gin',
    slug: 'thorn-gin',
    name: 'Thorn Gin',
    brand: 'Thorn',
    description: 'Premium Lithuanian dry gin — 40% ABV.',
    shortDescription: 'Lithuanian dry gin — 40% ABV.',
    categoryId: 'gin',
    image: imgThornGin,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 40,
    ean: '4770053240673',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'vd-thorn-pink',
    slug: 'thorn-pink-gin',
    name: 'Thorn Pink Gin',
    brand: 'Thorn',
    shortDescription: 'Pink gin — 37.5% ABV.',
    categoryId: 'gin',
    subCategoryId: 'pink',
    image: imgThornPinkGin,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 37.5,
    ean: '4770053240796',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Missed Call ─────────────────────────────────────────────────
  {
    id: 'vd-missed-call-london-dry',
    slug: 'missed-call-london-dry',
    name: 'Missed Call London Dry Gin (NEW)',
    brand: 'Missed Call',
    description: 'Bold London-Dry-style gin — 40% ABV.',
    shortDescription: 'London Dry gin — 40% ABV.',
    categoryId: 'gin',
    subCategoryId: 'dry',
    image: imgMissedCallDryGin,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 40,
    ean: '4770053242172',
    moq: 672,
    leadTimeWeeks: 4,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'vd-missed-call-strawberry',
    slug: 'missed-call-strawberry',
    name: 'Missed Call Strawberry Gin (NEW)',
    brand: 'Missed Call',
    shortDescription: 'Strawberry-infused gin — 37.5% ABV.',
    categoryId: 'gin',
    subCategoryId: 'strawberry',
    image: imgMissedCallStrawberryGin,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 37.5,
    ean: '4770053242189',
    moq: 672,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Obeliu Crafted ──────────────────────────────────────────────
  {
    id: 'vd-obeliu-crafted',
    slug: 'obeliu-crafted-vodka',
    name: 'Obeliu Crafted Vodka',
    brand: 'Obeliu Crafted',
    description: 'Small-batch Lithuanian vodka — 40% ABV. Premium presentation.',
    shortDescription: 'Crafted Lithuanian vodka — 40% ABV.',
    categoryId: 'vodka',
    image: imgObeliuCrafted,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 40,
    ean: '4770053239820',
    moq: 576,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Seven Senses ────────────────────────────────────────────────
  {
    id: 'vd-7senses-nuts',
    slug: 'seven-senses-nuts',
    name: 'Seven Senses Starka & Nuts',
    brand: '7 Senses',
    description: 'Aged grain spirit infused with nuts — 40% ABV.',
    shortDescription: 'Starka & nuts spirit — 40% ABV.',
    categoryId: 'spirit-drink',
    image: img7SensesNuts,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×0.5L',
    volume: '0.5L',
    alcoholContent: 40,
    ean: '4770053241519',
    moq: 855,
    leadTimeWeeks: 4,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'vd-7senses-herbs',
    slug: 'seven-senses-herbs',
    name: 'Seven Senses Herbs Liqueur',
    brand: '7 Senses',
    shortDescription: 'Herbal liqueur — 35% ABV.',
    categoryId: 'liqueur',
    image: img7SensesHerbal,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×0.5L',
    volume: '0.5L',
    alcoholContent: 35,
    ean: '4770053241526',
    moq: 855,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Barska Premium ─────────────────────────────────────────────
  {
    id: 'vd-barska-premium-1l',
    slug: 'barska-premium-vodka-1l',
    name: 'Barska Premium Vodka 1L',
    brand: 'Barska',
    description: 'Diplo\'s most strategic vodka SKU — Lithuanian premium grain vodka, 40% ABV.',
    shortDescription: 'Premium Lithuanian vodka — 1L, 40% ABV.',
    categoryId: 'vodka',
    subCategoryId: 'premium',
    image: imgBarskaPremium,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×1L',
    volume: '1L',
    alcoholContent: 40,
    ean: '4770053220224',
    moq: 468,
    leadTimeWeeks: 4,
    priceOnRequest: true,
    isFeatured: true,
  },
  {
    id: 'vd-barska-premium-07',
    slug: 'barska-premium-vodka-07l',
    name: 'Barska Premium Vodka 0.7L',
    brand: 'Barska',
    shortDescription: 'Premium vodka — 0.7L, 40% ABV.',
    categoryId: 'vodka',
    subCategoryId: 'premium',
    image: imgBarskaPremium,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×0.7L',
    volume: '0.7L',
    alcoholContent: 40,
    ean: '4770053235587',
    moq: 675,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-premium-05',
    slug: 'barska-premium-vodka-05l',
    name: 'Barska Premium Vodka 0.5L',
    brand: 'Barska',
    shortDescription: 'Premium vodka — 0.5L, 40% ABV.',
    categoryId: 'vodka',
    subCategoryId: 'premium',
    image: imgBarskaPremium,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.5L',
    volume: '0.5L',
    alcoholContent: 40,
    ean: '4770053235570',
    moq: 840,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Barska Classic ─────────────────────────────────────────────
  {
    id: 'vd-barska-classic-1l',
    slug: 'barska-classic-vodka-1l',
    name: 'Barska Classic Vodka 1L',
    brand: 'Barska',
    description: 'Classic-line Lithuanian vodka — 40% ABV.',
    shortDescription: 'Classic vodka — 1L, 40% ABV.',
    categoryId: 'vodka',
    subCategoryId: 'classic',
    image: imgBarskaClassic,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×1L',
    volume: '1L',
    alcoholContent: 40,
    ean: '4770053233217',
    moq: 408,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-classic-07',
    slug: 'barska-classic-vodka-07l',
    name: 'Barska Classic Vodka 0.7L',
    brand: 'Barska',
    shortDescription: 'Classic vodka — 0.7L.',
    categoryId: 'vodka',
    subCategoryId: 'classic',
    image: imgBarskaClassic,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '6×0.7L',
    volume: '0.7L',
    alcoholContent: 40,
    ean: '4770053234887',
    moq: 630,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-classic-05',
    slug: 'barska-classic-vodka-05l',
    name: 'Barska Classic Vodka 0.5L',
    brand: 'Barska',
    shortDescription: 'Classic vodka — 0.5L.',
    categoryId: 'vodka',
    subCategoryId: 'classic',
    image: imgBarskaClassic,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.5L',
    volume: '0.5L',
    alcoholContent: 40,
    ean: '4770053234870',
    moq: 840,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-classic-02',
    slug: 'barska-classic-vodka-02l',
    name: 'Barska Classic Vodka 0.2L',
    brand: 'Barska',
    shortDescription: 'Classic vodka — 0.2L pocket format.',
    categoryId: 'vodka',
    subCategoryId: 'classic',
    image: imgBarskaClassic200,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '20×0.2L',
    volume: '0.2L',
    alcoholContent: 40,
    ean: '4770053234900',
    moq: 1680,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Barska Flavoured ───────────────────────────────────────────
  {
    id: 'vd-barska-plum',
    slug: 'barska-plum-spirit-drink',
    name: 'Barska & Plum Spirit Drink',
    brand: 'Barska',
    shortDescription: 'Plum-flavoured spirit — 32% ABV, 0.5L.',
    categoryId: 'spirit-drink',
    image: imgBarskaPlum,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.5L',
    volume: '0.5L',
    alcoholContent: 32,
    ean: '4770053238588',
    moq: 840,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-lemon',
    slug: 'barska-lemon-spirit-drink',
    name: 'Barska & Lemon Spirit Drink',
    brand: 'Barska',
    shortDescription: 'Lemon-flavoured spirit — 32% ABV, 0.5L.',
    categoryId: 'spirit-drink',
    image: imgBarskaLemon,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.5L',
    volume: '0.5L',
    alcoholContent: 32,
    ean: '4770053238601',
    moq: 840,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-blackcurrant',
    slug: 'barska-blackcurrant',
    name: 'Barska & Blackcurrant',
    brand: 'Barska',
    shortDescription: 'Blackcurrant spirit drink — 32% ABV.',
    categoryId: 'spirit-drink',
    image: imgGalipoteBlackCurrant,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.5L',
    volume: '0.5L',
    alcoholContent: 32,
    ean: '4770053239516',
    moq: 840,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-cranberry',
    slug: 'barska-cranberry',
    name: 'Barska & Cranberry',
    brand: 'Barska',
    shortDescription: 'Cranberry spirit drink — 32% ABV.',
    categoryId: 'spirit-drink',
    image: imgBarskaCranberry,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.5L',
    volume: '0.5L',
    alcoholContent: 32,
    moq: 8400,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-barska-quince',
    slug: 'barska-quince',
    name: 'Barska & Quince',
    brand: 'Barska',
    shortDescription: 'Quince spirit drink — 32% ABV.',
    categoryId: 'spirit-drink',
    image: imgBarskaQuince,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.5L',
    volume: '0.5L',
    alcoholContent: 32,
    moq: 8400,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Admiral ────────────────────────────────────────────────────
  {
    id: 'vd-admiral-vodka',
    slug: 'admiral-vodka',
    name: 'Admiral Vodka',
    brand: 'Admiral',
    shortDescription: 'Lithuanian vodka — 40% ABV, 0.7L.',
    categoryId: 'vodka',
    image: imgAdmiralVodka,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '12×0.7L',
    volume: '0.7L',
    alcoholContent: 40,
    ean: '4770053222198',
    moq: 720,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-admiral-gin',
    slug: 'admiral-gin',
    name: 'Admiral Gin',
    brand: 'Admiral',
    shortDescription: 'Admiral-line gin — 37.5% ABV, 1L.',
    categoryId: 'gin',
    image: imgAdmiralGin,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×1L',
    volume: '1L',
    alcoholContent: 37.5,
    ean: '4770053242462',
    moq: 468,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },

  // ─── Čepkeliai ──────────────────────────────────────────────────
  {
    id: 'vd-cepkeliai-cowberry',
    slug: 'cepkeliai-cowberry',
    name: 'Čepkeliai Cowberry Spirit Drink',
    brand: 'Čepkeliai',
    description: 'Wild cowberry spirit — 36% ABV. Distinctive Lithuanian forest-berry profile.',
    shortDescription: 'Cowberry spirit — 36% ABV.',
    categoryId: 'spirit-drink',
    image: imgCepkeliaiCowberry,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×0.5L',
    volume: '0.5L',
    alcoholContent: 36,
    ean: '4770053221443',
    moq: 855,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-cepkeliai-forest',
    slug: 'cepkeliai-forest-berry',
    name: 'Čepkeliai Forest Berry Spirit Drink',
    brand: 'Čepkeliai',
    shortDescription: 'Forest-berry spirit — 36% ABV.',
    categoryId: 'spirit-drink',
    image: imgCepkeliaiForestberry,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×0.5L',
    volume: '0.5L',
    alcoholContent: 36,
    ean: '4770053238847',
    moq: 855,
    leadTimeWeeks: 4,
    priceOnRequest: true,
  },
  {
    id: 'vd-cepkeliai-cranberry',
    slug: 'cepkeliai-cranberry',
    name: 'Čepkeliai Cranberry Spirit Drink',
    brand: 'Čepkeliai',
    shortDescription: 'Cranberry spirit — 36% ABV.',
    categoryId: 'spirit-drink',
    image: imgCepkeliaiCraneBerry,
    origin: 'Lithuania',
    supplier: SUPPLIER,
    partnerType: 'EXCLUSIVE_PARTNER',
    partnerSlug: PARTNER,
    isOwnBrand: false,
    packing: '9×0.5L',
    volume: '0.5L',
    alcoholContent: 36,
    priceOnRequest: true,
  },
];

/** Carton-enriched export — see comment on `vilniausProductsRaw` above. */
export const vilniausProducts: Product[] = enrichProducts(vilniausProductsRaw);

/** Group helper — used by the Vilniaus landing page to show brand sections. */
export function vilniausByBrand(): Record<string, Product[]> {
  return vilniausProducts.reduce<Record<string, Product[]>>((acc, p) => {
    const brand = p.brand ?? 'Other';
    if (!acc[brand]) acc[brand] = [];
    acc[brand].push(p);
    return acc;
  }, {});
}
